[[insns-vaeskr1, Vector AES-128 Reverse KeySchedule]]
= vaeskr1.vi

Synopsis::
Vector AES-128 Reverse KeySchedule

Mnemonic::
vaeskr1.vi vd, vs2, uimm

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'uimm'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 'funct6'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| uimm | input  | -    | - | -  | Round Number (rnd)
| Vs2  | input  | 128  | 4 | 32 | Current Round key
| Vd   | output | 128  | 4 | 32 | Previous round key
|===

Description:: 
This instruction implements a single round of the reverse AES-128 KeySchedule.
It treats each 128-bit element group of `vs2` as the current AES round key.
The round number is stored in the unsigned 5-bit `rnd`immediate. Legal values are 1 - 10.
Out of range values signal an illegal instruction exception.

It applies a single AES-128 reverse KeySchedule round to each element, and
writes the 128-bit result to the corresponding element group in `vd`.

This instruction only returns the generated key to the same element group as the source.
If it is desired to have the same key in all vector groups, either the input vector groups
need to contain the same values, or the output from a particular group needs to be "broadcast"
to the other groups using an instruction such as vrgather.

This instruction ignores `vtype.vsew`. +
The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `EEW=32` elements to be processed and 
therefore must be a multiple of `EGS=4`. + 
Likewise, `vstart` must be a multiple of `EGS=4`

// This instruction requires that `Zvl128b` be implemented (i.e `VLEN>=128`).

Operation::
[source,pseudocode]
--
function clause execute (VAESESFK1(rcon, vs2)) = {
  vlen = tbd
  foreach (i from vstart to vlen) {
    let current : bits(128) = get_velem(vs2, EGW=128, i);
    let previous    : bits(128) = aes_128_reverse_key_schedule(rcon, current);
    set_velem(vd, EGW=128, i, previous);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===



