[[insns-vaes128k10, Vector AES-128 Generate round key 10]]
= vaes128k10.vv

Synopsis::
Vector AES-128 Generate round key 10

Mnemonic::
vae128k10.vv vd, vs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OPMVV'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'func3'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2=0'},
{bits: 1, name: 'vm'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
This instruction generates the final (10th) roundkey for AES-128 for consumption by
a subsequent AES-128 all rounds decryption instruction.
It treats each 128-bit element group of `vs2` as the current AES round key.
The round number is stored in the 5-bit `rnd`immediate. Legal values are 1 - 10.
Out of range values signal an illegal instruction exception.

It applies 10 AES-128 KeySchedule rounds to each element group, and
writes the 128-bit result to the corresponding element group in `vd`.

This instruction only returns the generated key to the same element group as the source.
If it is desired to have the same key in all vector groups, either the input vector groups
need to contain the same values, or the output from a particular group needs to be "broadcast"
to the other groups using an instruction such as vrgather.

This instruction treats `EEW=32` and `EGS=4`, regardless of `vtype.vsew`
In order to properly specify the number of elements, vl needs to be set to
vl = `vtype.vsew`/128. If vlstart is not zero, it needs to be scaled similarly.
This instruction requires that `Zvl128b` be implemented (i.e `VLEN>=128`).

Operation::
[source,pseudocode]
--
function clause execute (VAES128k10(rnd, vs2)) = {
  assert(VLEN>=128);
  // assert round key in range
  vlen = vl/EGS * vtype.SEW/EEW
  foreach (i from vlstart to vlen) {
    let rky : bits(128) = get_velem(vs2, EGW=128, i);
    foreach (rnd from 1 to 10)
      let rky    : bits(128) = aes_128_forward_key_schedule(rnd, rky);
    set_velem(vd, EGW=128, i, rky);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===