[[insns-vaeskf256-vv, Vector AES-256 Forward KeySchedule]]
= vaeskf256.vv

Synopsis::
Vector AES-256 Forward KeySchedule

Mnemonic::
vaeskf256.vv vd, vs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '???????'},
{bits: 5, name: 'vd'},
{bits: 3, name: '???'},
{bits: 5, name: 'vs1'},
{bits: 4, name: 'rnum'},
{bits: 8, name: '????????'},
]}
....

Description:: 
This instruction implements a single round of the forward AES-256 KeySchedule.
It concatenates the 128-bit element in `vs2` with the
128-bit element in `vs1` to create a 256-bit value.
From this, the next 128-bit round key is computed and written to `vd`.
The round number of the KeySchedule operation is stored in the 4-bit `rnum`
immediate.

Only a Vector-Vector version of this instruction is provided. To use this
instruction with the Vector-Scalar varients of the AES encrypt/decrypt
round function instructions, software can set `vl=1`.

This instruction treats `EEW=128`, regardless of `vtype.vsew`
and requires that `Zvl128b` be implemented (i.e `VLEN>=128`).
It _does not_ require that `EEW=128` be
supported for any other instruction.

[NOTE]
====
The AES-256 KeySchedule uses 8 32-bit words to compute the next 4 32-bit
words of the KeySchedule, while the round function consumes these words
in chunks of 128-bits.
====

Operation::
[source,sail]
--
function clause execute (VAESESM(rnum, vs1, vd)) = {
  assert(VLEN>=128);
  foreach (i from vlstart to vl) {
    let current : bits(256) = get_velem(vd, EEW=128, i) @
                              get_velem(vs1, EEW=128, i) ;
    let next    : bits(128) = aes_256_forward_key_schedule(rnum, current);
    set_velem(vd, EEW=128, i, next);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===




