[[insns-vaesef, Vector AES encrypt final round]]
= vaesef.[vv,vs]

Synopsis::
Vector AES final round encryption instruction.

Mnemonic::
vaesef.vv vd, vs2 +
vaesef.vs vd, vs2

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00011'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00011'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....
Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| vd  | input  | 128  | 4 | 32 | round state
| vs2 | input  | 128  | 4 | 32 | round key 
| vd  | output | 128  | 4 | 32 | new round state
|===

Description:: 
This instruction implements the final-round encryption function of the AES block cipher. The inputs and outputs to this
instruction are comprised of 128-bit element groups.  Each element group of source `vs2` holds the current round state
and each 128-bit element group of `vs2` holds the round key.
In the case of the `.vs` form of the instruction, element group 0 of the single register `vs2` holds a single element group that is used
as the round key for all of the element groups in `vd`. While in this case `vs2` is a single register,
`vd` can be a register group. 
The next round state output of each element group is produced by applying the SubBytes, ShiftRows, and AddRoundkey
steps to the corresponding inputs and is written to each `EGW=128` element group of `vd`.

This instruction must always be implemented such that its execution latency does not
depend on the data being operated upon.    

* SubBytes(state)
* ShiftRows(state)
* AddRoundKey(state,roundkey)

//(ASIICDOC limitation???: Can't end on a bullet)

[NOTE]
====
For the `.vs` form, since the least significant element group of register `vs2` is used for all element groups in register groups `vd`,
the destination vector register group `vd` cannot overlap with the single `vs2` vector register,
otherwise the instruction encoding is reserved.
====

Operation::
[source,sail]
--
function clause execute (VAESEF(vs2, vd, suffix) = {
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
    let keyelem = if suffix == "vv" then i else 0;
    let state : bits(128) = get_velem(vd, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, keyelem);
    let sb    : bits(128) = aes_fwd_sub_bytes(state);
    let sr    : bits(128) = aes_fwd_shift_rows(sb);
    let ark   : bits(128) = sr ^ rkey;
    set_velem(vd, EGW=128, i, ark);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===