[[insns-vaese256, Vector AES-256 encrypt all-rounds]]
= vaese256.[vv,vs]

Synopsis::
Vector AES-256 all rounds encryption instruction.

Mnemonic::
vaese256.vv vd, vs2, vs1 +
vaese256.vs vd, vs2, vs1

Encoding (Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| Vd  | input  | 128  | 4 | 32 | Plain text
| Vs1 | input  | 128  | 4 | 32 | AES-256 lower Cipher key
| Vs2 | input  | 128  | 4 | 32 | AES-256 upper Cipher key
| Vd  | output | 128  | 4 | 32 | Cipher text 
|===

Description:: 
This instruction implements the entire AES-128 block cipher decryption
function. It internally generates each of the round keys and performs each of the rounds.

It treats each `EGW=128` element group of `vd` as the plaintext
and concatenates `EGW=128` element groups of `vs1` and `vs2` as the 256-bit encryption key.

The result (i.e. the ciphertext) is written to `EGW=128` element groups of `vd`.

This instruction operates on element groups in the source and destination registers

This instruction requires that: +

* `vl` is an integral multiple of `EGS`
* `vstart` is an integral multiple of `EGS`

This instruction ignores`SEW`



Operation::
[source,sail]
--
function clause execute (VAES256E(vs1, vs2, vd,)) = {
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS
  elementgroups = (vl/EGS)
  egstart = (vstart/EGS)
  
  foreach (i from egstart to elementgroups) {
    let keyelem = if vv then i else 0;
    state : bits(128) = get_velem(vd, EGW=128, i);
    ekey  : bits(256) = get_velem(vs1, EGW=128, keyelem) @
                        get_velem(vs2, EGW=128, keyelem) ;
    rkey  : bits(128) = ekey[127..0];
    state = state ^ rkey;
    foreach(r from 0 to 12) {
      state = aes_fwd_sub_bytes(state);
      state = aes_fwd_shift_rows(state);
      state = aes_fwd_mix_columns(state);
      state = state ^ rkey;
      rkey  = aes_256_forward_key_schedule(ekey);
      ekey  = rkey @ ekey[256..128];
    }
    state = aes_fwd_sub_bytes(state);
    state = aes_fwd_shift_rows(state);
    state = state ^ rkey;
    set_velem(vd, EGW=128, i, state);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvknf>>
| v0.1.0
| In Development
|===



