[[insns-vaesz, Vector AES round zero]]
= vaesz.vs

Synopsis::
Vector AES round zero encryption/decryption instruction.

Mnemonic::
vaesz.vs vd, vs2, vs1

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'funct5'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....
Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| vd  | input  | 128  | 4 | 32 | round state
| vs2 | input  | 128  | 4 | 32 | round key 
| vd  | output | 128  | 4 | 32 | new round state
|===

Description:: 
Perform the round-0 function of the AES block cipher. The function is identical for encryption and decryption.

The inputs and outputs to this instruction are comprised of 128-bit element groups.
Each element group of source `vs2` holds the current round state
and each 128-bit element group of `vs1` holds the round key.
There is only a `.vs` form of the instruction. Element group 0 of the single register `vs1` holds a single element group
that is used as the round key for all of the element groups in `vs2`. While in this case `vs1` is a single register, both
`vs2` and `vd` can be register groups. 
The next round state output of each element group is produced by applying the AddRoundkey
step to the corresponding inputs. This instruction must always be implemented such that its execution latency does not
depend on the data being operated upon.    

Note::
This instruction is needed to avoid the need to "splat" a 128-bit vector register group when the round key is the same for
all 128-bit "lanes". Such a splat would typically be implemented with a `vrgather` instruction which would hurt performance
in many implementations. 
This instruction only exists in the .vs form because the .vv form would be identical to the VXOR instruction.

- AddRoundKey(state,roundkey)

This instruction operates on element groups in the source and destination registers

Note::
This is true for all .vs instructions in the Vector Crypto Extensions - COPY THIS TO THE OTHER INSTRUCTIONS
Since the least significant element group of register `vs1` is used for all element groups in register groups `vd`
and `vs2`, the destination vector register group cannot overlap with the single `vs` vector register,
otherwise the instruction encoding is reserved.


Operation::
[source,sail]
--
function clause execute (VAESZ(vs1, vd) = {
  // calculate the number of element groups (eg)
  eg = (vl/EGS)  
  foreach (i from vstart to eg) {
    let state : bits(128) = get_velem(vd, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, i);
    let ark   : bits(128) = state ^ rkey;
    set_velem(vd, EGW=128, i, ark);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===