[[insns-vaesef, Vector AES encrypt final round]]
= vaesef.[vv,vs]

Synopsis::
Vector AES final round encryption instruction.

Mnemonic::
vaesef.vv vd, vs2 +
vaesef.vs vd, vs2

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'funct5'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'funct5'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....
Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| vd  | input  | 128  | 4 | 32 | round state
| vs2 | input  | 128  | 4 | 32 | round key 
| vd  | output | 128  | 4 | 32 | new round state
|===

Description:: 
This instruction implements the final-round encryption function of the AES block cipher. The inputs and outputs to this
instruction are comprised of 128-bit element groups.  Each element group of source `vs2` holds the current round state
and each 128-bit element group of `vs2` holds the round key.
In the case of the `.vs` form of the instruction, element group 0 of the single register `vs2` holds a single element group that is used
as the round key for all of the element groups in `vd`. While in this case `vs2` is a single register,
`vd` can be a register group. 
The next round state output of each element group is produced by applying the SubBytes, ShiftRows, and AddRoundkey
steps to the corresponding inputs. This instruction must always be implemented such that its execution latency does not
depend on the data being operated upon.    

* SubBytes(state)
* ShiftRows(state)
* AddRoundKey(state,roundkey)

//(ASIICDOC limitation???: Can't end on a bullet)

Note::
This is true for all .vs instructions in the Vector Crypto Extensions - COPY THIS TO THE OTHER INSTRUCTIONS
Since the least significant element group of register `vs2` is used for all element groups in register groups `vd`
and `vs2`, the destination vector register group cannot overlap with the single `vs` vector register,
otherwise the instruction encoding is reserved.


Operation::
[source,sail]
--
function clause execute (VAESEF(vs2, vd) = {
  // calculate the number of element groups (eg)
  eg = (vl/EGS)  
  foreach (i from vstart to eg) {
    let state : bits(128) = get_velem(vd, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, i);
    let sb    : bits(128) = aes_fwd_sub_bytes(state);
    let sr    : bits(128) = aes_fwd_shift_rows(sb);
    let ark   : bits(128) = sr ^ rkey;
    set_velem(vd, EGW=128, i, ark);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===