[[insns-vaesds, Vector AES decrypt final round]]
= vaesds.[vv,vs]

Synopsis::
Vector AES final round decryption instruction.

Mnemonic::
vaesds.[vv,vs] vd, vs1, vs2

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '???????'},
{bits: 5, name: 'vd'},
{bits: 3, name: '???'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 7, name: '???????'},
]}
....

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '???????'},
{bits: 5, name: 'vd'},
{bits: 3, name: '???'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 7, name: '???????'},
]}
....

Description:: 
This instruction implements the final-round decryption function of the AES
block cipher for all parameterisations.
It treats each element of `vs1` as the current AES round state,
and elements of `vs2` as the round key.
The Vector-Vector (VV) variant decrypts elements of `vs1` under corresponding
elements of `vs2`.
The Vector-Scalar (VV) variant dwcrypts elements of `vs1` under the
zeroth element of `vs2`.
The result (i.e. the next round state) is written to elements of `vd`.

This instruction treats `EEW=128`, regardless of `vtype.vsew`
and requires that `Zvl128b` be implemented (i.e `VLEN>=128`).
It _does not_ require that `EEW=128` be
supported for any other instruction.

Operation::
[source,sail]
--
function clause execute (VAESDS(vs2, vs1, vd, vv)) = {
  assert(VLEN>=128);
  foreach (i from vlstart to vl) {
    let keyelem = if vv then i else 0;
    let state : bits(128) = get_velem(vs1, EEW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EEW=128, keyelem);
    let sr    : bits(128) = aes_inv_shift_rows(state);
    let sb    : bits(128) = aes_inv_sub_bytes(sr);
    let ark   : bits(128) = sb ^ rkey;
    set_velem(vd, EEW=128, i, ark);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===


