[[insns-vaeskf2, Vector AES-256 Forward KeySchedule]]
= vaeskf2.vi

Synopsis::
Vector AES-256 Forward KeySchedule

Mnemonic::
vaeskf2.vi vd, vs2, uimm

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPIVI'},
{bits: 5, name: 'uimm'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 'funct6'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| Vd   | input  | 128  | 4 | 32 | Previous Round key
| uimm | input  | -    | - | -  | Round Number (rnd)
| Vs2  | input  | 128  | 4 | 32 | Current Round key
| Vd   | output | 128  | 4 | 32 | Next round key
|===

Description:: 
This instruction implements a single round of the forward AES-256 KeySchedule.
It treats each `EGW=128` element group of `vs2` as the current AES round key,
and each `EGW=128` element group of `vd` as the previous AES round key.
The round number is stored in the unsigned 5-bit `rnd` immediate. Legal values are 2 - 14.
Out of range values signal an illegal instruction exception.

It applies a single AES-256 KeySchedule round to each element group, and
writes the 128-bit result to the corresponding element group in `vd`.

This instruction only returns the generated key to the same element group as the source.
If it is desired to have the same key in all vector groups, either the input vector groups
need to contain the same values, or the output from a particular group needs to be "broadcast"
to the other groups using an instruction such as vrgather.

This instruction ignores `vtype.vsew`. +
The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `EEW=32` elements to be processed and 
therefore must be a multiple of `EGS=4`. + 
Likewise, `vstart` must be a multiple of `EGS=4`

[NOTE]
====
The AES-256 KeySchedule uses 8 32-bit words to compute the next 4 32-bit
words of the KeySchedule, while the round function consumes these words
in chunks of 128-bits.
====


Operation::
[source,pseudocode]
--
function clause execute (VAESESFK1(rnd, vd, vs2)) = {
  // assert round key in range
  vlen = vl/EGS
  foreach (i from vstart to vlen) {
    let current : bits(128) = get_velem(vs2, EGW=128, i);
    let previous : bits(128) = get_velem(vd, EGW=128, i);
    let next    : bits(128) = aes_256_forward_key_schedule(rnd, current, previous);
    set_velem(vd, EGW=128, i, next);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===
