[[insns-vaesdm, Vector AES decrypt middle round]]
= vaesdm.[vv,vs]

Synopsis::
Vector AES middle round decryption instruction.

Mnemonic::
vaesdsm.vv vd, vs2 +
vaesdsm.vs vd, vs2

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPIVV'},
{bits: 5, name: 'funct5'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'funct5'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| Vd  | input  | 128  | 4 | 32 | round state
| Vs2 | input  | 128  | 4 | 32 | Round key
| Vd  | output | 128  | 4 | 32 | new round state
|===

Description:: 
This instruction implements the middle-round decryption function of the AES
block cipher.

The inputs and outputs to this instruction are comprised of 128-bit element groups.  Each `EGW=128` element group of source `vd` holds the current round state and each `EGW=128` element group of `vs1` holds the round key. Each `EGW=128` element group next round state output is produced by applying the ShiftRows, SubBytes,  and AddRoundkey steps to the corresponding inputs.

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.    

- InvShiftRows(state)
- InvSubBytes(state)
- AddRoundKey(state,roundkey)


This instruction operates on element groups in the source and destination registers:

This instruction ignores `vtype.vsew`. +
The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `EEW=32` elements to be processed and 
therefore must be a multiple of `EGS=4`. + 

Operation::
[source,sail]
--
function clause execute (VAESDSM(vs1, vd, vv)) = {
  // calculate the number of element groups (eg)
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS
  elementgroups = (vl/EGS)
  egstart = (vstart/EGS)


  foreach (i from egstart to elementgroups) {
    let state : bits(128) = get_velem(vs1, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, i);
    let sr    : bits(128) = aes_inv_shift_rows(state);
    let sb    : bits(128) = aes_inv_sub_bytes(sr);
    let ark   : bits(128) = sb ^ rkey;
    let mix   : bits(128) = aes_inv_mix_columns(ark);
    set_velem(vd, EGW=128, i, mix);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===