[[insns-vaesdm, Vector AES decrypt middle round]]
= vaesdm.[vv,vs]

Synopsis::
Vector AES middle round decryption instruction.

Mnemonic::
vaesdm.vv vd, vs2 +
vaesdm.vs vd, vs2

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| Vd  | input  | 128  | 4 | 32 | round state
| Vs2 | input  | 128  | 4 | 32 | Round key
| Vd  | output | 128  | 4 | 32 | new round state
|===

Description:: 
This instruction implements the middle-round decryption function of the AES
block cipher.

The inputs and outputs to this instruction are comprised of 128-bit element groups.  Each `EGW=128` element group of source `vd` holds the current round state and each `EGW=128` element group of `vs2` holds the round key.

In the case of the `.vs` form of the instruction, element group 0 of the single register `vs2` holds a single element group that is used
as the round key for all of the element groups in `vd`. While in this case `vs2` is a single register,
`vd` can be a register group. 

Each `EGW=128` element group next round state output is produced by applying the InvShiftRows, InvSubBytes, AddRoundkey and InvMixColumns steps to the corresponding inputs and is written to each `EGW=128` element group of `vd`.

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.    

- InvShiftRows(state)
- InvSubBytes(state)
- AddRoundKey(state,roundkey)
- InvMixColumns(state)

The result (i.e. the next round state) is written to each `EGW=128` element group of `vd`.

This instruction ignores `vtype.vsew`. +
The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `EEW=32` elements to be processed and 
therefore must be a multiple of `EGS=4`. + 

Note::
For the `.vs` form, since the least significant element group of register `vs2` is used for all element groups in register groups `vd`
and `vs2`, the destination vector register group cannot overlap with the single `vs` vector register,
otherwise the instruction encoding is reserved.


Operation::
[source,sail]
--
function clause execute (VAESDM(vs1, vd, suffix)) = {
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
    let keyelem = if suffix == "vv" then i else 0;
    let state : bits(128) = get_velem(vs1, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, keyelem);
    let sr    : bits(128) = aes_inv_shift_rows(state);
    let sb    : bits(128) = aes_inv_sub_bytes(sr);
    let ark   : bits(128) = sb ^ rkey;
    let mix   : bits(128) = aes_inv_mix_columns(ark);
    set_velem(vd, EGW=128, i, mix);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===