[[insns-vaesz, Vector AES round zero]]
= vaesz.vs

Synopsis::
Vector AES round zero encryption/decryption instruction.

Mnemonic::
vaesz.vs vd, vs2

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '00111'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....
Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|SEW
|Definition

| vd  | input  | 128  | 4 | 32 | round state
| vs2 | input  | 128  | 4 | 32 | round key 
| vd  | output | 128  | 4 | 32 | new round state
|===

Description:: 
`SEW` must be 32, otherwise the instruction encoding is reserved.

Perform the round-0 function of the AES block cipher. The function is identical for encryption and decryption.

Element group 0 of the single register `vs2` holds a single element group that is used
as the round key for all of the element groups in `vd`. While `vs2` is a single register,
`vd` can be a register group; the instruction encoding is reserved if `vd` register group overlaps with `vs2`. 

The inputs and outputs to this instruction are comprised of 128-bit element groups.
Each element group of source `vs2` holds the current round state
and each 128-bit element group of `vs1` holds the round key.
There is only a `.vs` form of the instruction. Element group 0 of the single register `vs2` holds a single element group
that is used as the round key for all of the element groups in `vs2`. While in this case `vs2` is a single register, 
`vd` can be a register group. 
The next round state output of each element group is produced by applying the AddRoundkey
step to the corresponding inputs.



- AddRoundKey(state,roundkey)

[NOTE]
====
This instruction is needed to avoid the need to "splat" a 128-bit vector register group when the round key is the same for
all 128-bit "lanes". Such a splat would typically be implemented with a `vrgather` instruction which would hurt performance
in many implementations. 
This instruction only exists in the `.vs` form because the `.vv` form would be identical to the VXOR instruction.
====

This instruction operates on element groups in the source and destination registers.

This instruction must always be implemented such that its execution latency does not
depend on the data being operated upon.

The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `SEW=32` elements to be processed and 
therefore must be a multiple of `EGS=4`. + 
Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,sail]
--
function clause execute (VAESZ(vs2, vd) = {
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
    let state : bits(128) = get_velem(vd, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, 0);
    let ark   : bits(128) = state ^ rkey;
    set_velem(vd, EGW=128, i, ark);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===
