[[insns-vaesdm, Vector AES decrypt middle round]]
= vaesdm.v

Synopsis::
Vector AES middle round decryption instruction.

Mnemonic::
vaesdsm.v vd, vs1

Encoding (Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OPMVV'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'func3'},
{bits: 5, name: 'vs1'},
{bits: 5, name: '?????'},
{bits: 1, name: 'vm'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
This instruction implements the middle-round decryption function of the AES
block cipher.

The inputs and outputs to this instruction are comprised of 128-bit element groups.  Each `EGW=128` element group of source `vd` holds the current round state and each `EGW=128` element group of `vs1` holds the round key. Each `EGW=128` element group next round state output is produced by applying the ShiftRows, SubBytes,  and AddRoundkey steps to the corresponding inputs.

This instruction must always be implemented such that its execution latency does not depend
on the data being operated upon.    

- ShiftRows(state)
- SubBytes(state)
- AddRoundKey(state,roundkey)


This instruction operates on element groups in the source and destination registers:

- Element Group Width (EGW) = 128 bits
- Effective Element Width (EEW) = 32 bits
- Element Group Size (EGS) = 4 elements


This instruction treats `EEW=32` and `EGS=4`, regardless of `vtype.vsew`
In order to properly specify the number of elements, vl needs to be set to
vl = `vtype.vsew`/128. If vlstart is not zero, it needs to be scaled similarly.
This instruction requires that `Zvl128b` be implemented (i.e `VLEN>=128`).

Operation::
[source,sail]
--
function clause execute (VAESDSM(vs1, vd, vv)) = {
  assert(VLEN>=128);
  // calculate the number of element groups (eg)
  eg = (vl/EGS)  
  foreach (i from vlstart to eg) {
    let state : bits(128) = get_velem(vs1, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, i);
    let sr    : bits(128) = aes_inv_shift_rows(state);
    let sb    : bits(128) = aes_inv_sub_bytes(sr);
    let ark   : bits(128) = sb ^ rkey;
    let mix   : bits(128) = aes_inv_mix_columns(ark);
    set_velem(vd, EGW=128, i, mix);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===