[[insns-vaeskf192-vv, Vector AES-192 Forward KeySchedule]]
= vaeskf192.vv

Synopsis::
Vector AES-192 Forward KeySchedule

Mnemonic::
vaeskf192.vv vd, vs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '???????'},
{bits: 5, name: 'vd'},
{bits: 3, name: '???'},
{bits: 5, name: 'vs1'},
{bits: 4, name: 'rnum'},
{bits: 8, name: '????????'},
]}
....

Description:: 
This instruction implements a single round of the forward AES-192 KeySchedule.
It concatenates the top half of the element in `vs1` with the whole
element in `vd` to create a 192-bit value.
The round number of the KeySchedule operation is stored in the 4-bit `rnum`
immediate.
From this, the next 128-bit round key is computed and written to `vd`.

Only a Vector-Vector version of this instruction is provided. To use this
instruction with the Vector-Scalar varients of the AES encrypt/decrypt
round function instructions, software can set `vl=1`.

This instruction treats `EEW=128`, regardless of `vtype.vsew`
and requires that `Zvl128b` be implemented (i.e `VLEN>=128`).
It _does not_ require that `EEW=128` be
supported for any other instruction.

[NOTE]
====
The AES-192 KeySchedule uses 6 32-bit words to compute the next 4 32-bit
words of the KeySchedule, while the round function consumes these words
in chunks of 128-bits.
====

Operation::
[source,sail]
--
function clause execute (VAESESM(rnum, vs1, vd)) = {
  assert(VLEN>=128);
  foreach (i from vlstart to vl) {
    let current : bits(192) = get_velem(vd, EEW=128, i) @
                              get_velem(vs1, EEW=128, i) [128..64]
    let next    : bits(128) = aes_192_forward_key_schedule(rnum, current);
    set_velem(vd, EEW=128, i, next);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===



