[[insns-vaesem, Vector AES encrypt middle round]]
= vaesem

Synopsis::
Vector AES middle round encryption instruction.

Mnemonic::
vaesem.vv vd, vs2, vs1 +
vaesem.vs vd, vs2, vs1

Encoding (Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
This instruction implements the middle-round function of the AES block cipher.
It treats each `EGW=128` element group of `vs2` as the current AES round state,
and each `EGW=128` element group of `vs1` as the round key.

The result (i.e. the next round state) is written to each `EGW=128` element group of `vd`.

This instruction treats `EEW=32` and `EGS=4`, regardless of `vtype.vsew`
In order to properly specify the number of elements, vl needs to be set to
vl = `vtype.vsew`/128. If vstart is not zero, it needs to be scaled similarly.
This instruction requires that `Zvl128b` be implemented (i.e `VLEN>=128`).

Operation::
[source,pseudocode]
--
function clause execute (VAESESM(vs2, vd, vv)) = {
  assert(VLEN>=128);
  foreach (i from vstart to vl) {
    let state : bits(128) = get_velem(vd, EGW=128, i);
    let rkey  : bits(128) = get_velem(vs2, EGW=128, i);
    let sb    : bits(128) = aes_fwd_sub_bytes(state);
    let sr    : bits(128) = aes_fwd_shift_rows(sb);
    let mix   : bits(128) = aes_fwd_mix_columns(sr);
    let ark   : bits(128) = mix ^ rkey;
    set_velem(vd, EGW=128, i, ark);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkns>>
| v0.1.0
| In Development
|===