[[insns-vclmulh, Vector Carry-less Multiply Return High Half]]
= vclmulh.[vv,vx]

Synopsis::
Vector Carry-less Multiply Upper Part by vector or scalar.

Mnemonic::
vclmulh.vv vd, vs2, vs1, vm +
vclmulh.vx vd, vs2, rs1, vm

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPIVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '001101'},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPIVX'},
{bits: 5, name: 'rs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: '001101'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| Vs1 | input  | SEW  | 1 | SEW | multiplier
| Vs2 | input  | SEW  | 1 | SEW | multiplicand
| Vd  | output | SEW  | 1 | SEW | carry-less product high
|===

Description:: 
This instruction performs a carry-less multiply operation to all
active elements in the vector register group specified by `vs2`.
The other operand can come from a vector register group `vs1`, or a scalar
integer register `rs1`.
For the scalar integer register, the operand is zero extended or truncated
to `SEW` bits as appropriate.

For each element, the `SEW-1` upper bits of the `(2*SEW-1)`-bit result are 
returned. The most significant bit of each `SEW`-wide element is always 0.

This instruction is only defined for `SEW=64`. The use of any other SEW with this instruction is reserved.

Operation::
[source,sail]
--
function clause execute (VCLMULH(vs2, vs1, vd, suffix)) = {

  foreach (i from vstart to vl-1) {
    let op1 : bits (64) = if suffix =="vv" then get_velem(vs1, i) else X(vs1);
    let op2 : bits (64) = get_velem(vs2, i);
    let product : bits (64) = clmulh(op1, op2, width);
    set_velem(vd, i, product);
  }
  RETIRE_SUCCESS
}

function clmulh(x, y, width) = {
  let result : bits(width) = 0;
  foreach (i from 1 to (width - 1)) {
    if y[i] == 1 then result = result ^ (x >> (width - i));
  }
  result
}

--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkb>>
| v0.1.0
| In Development
|===




