[[insns-vclmulgf, Vector Carryless Multiply over Galois-Field 2^128]]
= vclmulgf.vi

Synopsis::
Vector Carryless Multiply over Galois-Field 2^128

Mnemonic::
vclmulgf.vv vd, vs2, vs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
This instruction performs a multiply between two 128-bit polynomials modulo
x^128^ + x^7^ + x^2^ + x + 1

It treats each EGW=128 element group of `vs1` and `vs2` as the input polynomials.
This instruction is intended to be used to implement a GHASH~H~ as defined in NIST Special Publication 800-38D
"Recommendation for Block Cipher Modes of Operation:
Galois/Counter Mode (GCM) and GMAC". See
link:https://csrc.nist.gov/publications/detail/sp/800-38d/final[here]
This specification orders the coefficients in increasing order from left to right x~0~x~1~...x~127~
for a polynomial x~0~ + x~1~u +x~2~ u^2^ + ... + x~127~u^127^.

In order to match the GHASH specification, the bits within bytes are reversed internally to the instruction
so that the least significant bit is on the left.

This instruction effectively applies a single 128x128 carryless multiply producing a 255-bit product which it reduces
by multiplying the most significant 127 bits by the irreducible polynomial x^128^ + x^7^ + x^2^ + x + 1,
and adding it to the least significant 128 bits,
producing a 128-bit result which is written to the corresponding element group in `vd`.



This instruction treats `EEW=32`, regardless of `vtype.vsew` and requires that
 `Zvl128b`be implemented (i.e `VLEN>=128`).

Operation::
[source,pseudocode]
--
function clause execute (VCLMULGF(vs2, vs1, vd)) = {
  assert(VLEN>=128);
  // TODO: Add in bit reordering
  foreach (i from vstart to vl) {
      set_velem(vd, i, clmul(get_velem(vs1,i), get_velem(vs2,i)));
  }
  // TODO: Add in reduction code
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkg>>
| v0.1.0
| In Development
|===