[[insns-vclmul, Vector Carry-less Multiply]]
= vclmul.[vv,vx]

Synopsis::
Vector Carry-less Multiply by vector or immediate - returning low half of product.

Mnemonic::
vclmul.vv vd, vs2, vs1 +
vclmul.vx vd, vs2, rs1

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'rs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
This instruction performs a carry-less multiply operation to all
active elements in the vector register group specified by `vs2`.
It returns the least significant EEW bits of the product.

This instruction is only defined for `SEW=64`. The use of any other SEW with this instruction is reserved.

Note::
The 64-bit carryless multiply is used for implementing GCM in the absence of the <<vclmulgf,insns-vclmulgf>> instruction.
We do not make these two instructions exclusive as the 64-bit carryless multiply is readily derived from the `vclmulgf`
logic and can have utility in other areas. Likewise, we treat other SEW values as reserved so as not to preclude
future extensions from using this opcode with different element widths as may be used in generating CRCs, for example.   

The other operand can come from a vector register group `vs1`, or a scalar
integer register `rs1`.
For the scalar integer register, the operand is zero extended or truncated
to 64 bits as appropriate.

Operation::
[source,sail]
--
function clmul(x, y, EEW) = { // TODO: not real Sail Code yet
  result : bits(EEW) = zeros();
  foreach (i from 0 to (EEW - 1)) {
    if y[i] == bitone then result = result ^ (x << i);
  };
  result
}

function clause execute (VCLMUL_VV(vs2, vs1, vd)) = {
  foreach (i from vstart to vl) {
      set_velem(vd, i, clmul(get_velem(vs1,i), get_velem(vs2,i)));
  }
  RETIRE_SUCCESS
}

function clause execute (VCLMUL_VX(vs2, rs1, vd)) = {
  foreach (i from vstart to vl) {
      set_velem(vd, i, clmul(X(rs1), get_velem(vs2,i)));
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkb>>
| v0.1.0
| In Development
|===



