[[insns-vghmac, Vector GHASH Multiply Accumulate]]
= vghmac.vv

Synopsis::
Vector Carryless Multiply Accumulate over GHASH Galois-Field

Mnemonic::
vghmac.vv vd, vs2, vs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101100'},
]}
....
Reserved Encodings::
* `SEW` is any value other than 32 

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|SEW
|Definition

| Vd  | input  | 128  | 4 | 32 | Partial hash (Y~i~)
| Vs1 | input  | 128  | 4 | 32 | Hash Subkey (H)
| Vs2 | input  | 128  | 4 | 32 | Block Cipher output (X~i+1~)
| Vd  | output | 128  | 4 | 32 | Partial-hash (Y~i+1~)
|===

Description:: 
A single "iteration" of the GHASH~H~ algorithm is performed.

GHASH~H~ is defined in 
link:https://csrc.nist.gov/publications/detail/sp/800-38d/final[NIST Special Publication 800-38D]
 "Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM) and GMAC"
(NIST Specification).
It produces the next partial hash (Y~i+1~) by multiplying (over GF(2^128^)) the current partial
hash (Y~i~) by the Hash Subkey (H) and adding (over GF[2]) this product to the next block of
cipher text (X~i+1~).
The multiplication over GF(2^128^) is a carryless multiply of two 128-bit polynomials
modulo the irreducible polynomial (x^128^ + x^7^ + x^2^ + x + 1) used by GHASH.

The NIST Specification orders the coefficients from left to right x~0~x~1~x~2~...x~127~
for a polynomial x~0~ + x~1~u +x~2~ u^2^ + ... + x~127~u^127^. This is effectively a big-endian representation
that additionally has the bits within the bytes ordered from left to right (i.e., 0,1,2,3,4,5,6,7).
In the RISC-V little-endian register representation, the byte order is swapped. This instruction internally
performs bit swaps to put the bits within bytes in the standard ordering from right to left
(i.e., 7,6,5,4,3,2,1,0). 

[Note]
====
We are bit-reversing the bytes of inputs and outputs so that the intermediate values are consistent
with the NIST specification. These reversals are inexpensive to implement as they unconditionally
swap bit positions and therefore do not require any logic.
====

// [Note]
// ====
// To understand the inputs from the algorithm point of view, they can be viewed as being bit-serial
// with the least significant bit (i.e. bit 0) arriving first and the subsequent bits being concatenated on the right.
// The first group of 8 bits is byte 0, the second is byte 1 and so on until byte 15.
// When we represent these elements in a RISC-V vector element group, byte 0 is the rightmost byte and byte 15 is
// the leftmost. Since the leftmost bit of each byte is now holding the lsb, we perform a bit-reverse operation to
// get the bits in the order 7 to 0.
// Now the element group holds the most significant bit (i.e., bit 127) on the left and the least significant bit
// (i.e., bit 0) on the right. While this is the reverse of how bits are shown in the specification, it is in the
// order that we are used to, and allows us to use standard polynomial multiply operations and to use 0x87 as the least
// significant 128 bits of the irreducible polynomial.
// ====

The operation can be compactly defined as
Y~i+1~ = (Y~i~ &#183; H) ^ X~i+1~ `// with Y~0~ = X~0~`

Each EGW=128 element group of `vs1` and `vs2` are the input polynomials.

// The multiplication over GF(2^128^) is defined in the spec as follows:
//
// . Let `R` be the bit string `11100001 || 0^120^`
// . Let `x~0~x~1~...x~127~` denote the sequence of bits in `X`.
// . Let `Z~0~ = 0^128^` and `V~0~ = Y`.
// . For i = 0 to 127 // calculate blocks `Z~i+1~` and `V~i+1~` as follows:
// .. `Z~i+1~ := X~i~ ? (Z~i~ ^ V~i~), Z~i~`
// .. `V~i+1~ := (V~i~ & 1) ? (V~i~ >> 1) &#8853; R, V~i~ >> 1`
// . Return `Z~128~`.

// [Note]
// ====
// In the above definition, the least significant bit is on the left and the most significant it on the right.
// Shifting to the right by one place is effectively multiplying by 2.
// The V value is multiplied by 2 and then reduced if the shifted off MSB==1.
// This allows the value to remain representable in 128 bits.

// This instruction effectively applies a single 128x128 carryless multiply producing a 255-bit product which it reduces
// by multiplying the most significant 127 bits by the irreducible polynomial x^128^ + x^7^ + x^2^ + x + 1,
// and adding it to the least significant 128 bits,
// producing a 128-bit result which is written to the corresponding element group in `vd`.
// ====

The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `SEW=32` elements to be processed and
therefore must be a multiple of `EGS=4`. +
Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,pseudocode]
--
function clause execute (VGHMAC(vs2, vs1, vd)) = {
  // operands are input with bits reversed in each byte
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0)   //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
    let Y = brev8(get_velem(vd,EGW=128,i));  // current partial-hash
    let H = brev8(get_velem(vs1,EGW=128,i)); // Hash subkey
    let X = get_velem(vs2,EGW=128,i);       // next block cipher output
    let Z : bits(128) = 0;

    for (int bit = 0; bit < 128; bit++) {
      if bit_to_bool(Y[bit])
        Z ^= H

      bool reduce = bit_to_bool(H[127]);
      H = H << 1; // left shift H by 1
      if (reduce)
        H ^= 0x87; // Reduce using x^7 + x^2 + x^1 + 1 polynomial
    }

    let sum[127:0] = brev8(Z) ^ X; // bit reverse bytes of product to get back to GCM standard ordering

    let result = sum[127:0]; 
    set_velem(vd, EGW=128, i, result);
  }
  RETIRE_SUCCESS



}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkg>>
| v0.1.0
| In Development
|===
