[[insns-vsha2ms, Vector SHA-2 Message Schedule]]
= vsha2ms.vv

Synopsis::
Vector SHA-2 message schedule.

Mnemonic::
vsha2ms.vv vd, vs2, vs1

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPIVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| Vd  | input  | 4*SEW  | 4 | SEW | Message words {W[3],  W[2],  W[1],  W[0]}
| Vs1 | input  | 4*SEW  | 4 | SEW | Message words {W[11], W[10], W[9],  W[4]}
| Vs2 | input  | 4*SEW  | 4 | SEW | Message words {W[15], W[14], W[13], W[12]}
| Vd  | output | 4*SEW  | 4 | SEW | Message words {W[19], W[18], W[17], W[16]}
|===

Description::

- When `SEW`=32, this instruction implements 4 rounds of SHA-256 message
schedule expansion with EGW=128
- When `SEW`=64, this instruction implements 4 rounds of SHA-512 message
schedule expansion with EGW=256

If SEW is other than 32 or 64, this instruction takes the undefined instruction exception.

This instruction takes in a subset of the last 16 message-schedule `SEW`-sized "words"
and produces the next 4 message-schedule words.

Four `SEW` message schedule words are packed into each `EGW` element group of the
source and destination registers.

This instructions takes in 11 of the last 16 words of the message schedule. The last 16
words of the message schedule are shown here in an element group.
The subscripts show the relative age, where W~0~ is the oldest and W~15~ is the most recent
of the 16 words.

`{W~3~, W~2~, W~1~, W~0~} +
{W~7~, W~6~, W~5~, W~4~} +
{W~11~, W~10~, W~9~, W~8~} +
{W~15~, W~14~, W~13~, W~12~}`

Since W~5~ through W~8~ are not needed in these calculations, we are able to compact these into
three element groups

`{W~3~, W~2~, W~1~, W~0~} +
{W~11~, W~10~, W~9~, W~4~} +
{W~15~, W~14~, W~13~, W~12~}`

[TIP]
.Note to software developers
====
The combining of these element groups as shown here can readily be performing using a vector
vmerge instruction with the appropriate mask

`vmerge {W~11~, W~10~, W~9~, W~4~}, {W~11~, W~10~, W~9~, W~8~}, {W~7~, W~6~, W~5~, W~4~}, V0`


====

The instruction calculates the next 4 words of the message schedule:

`{W~19~, W~18~, W~17~, W~16~}`

The number of words to be processed is `vl`/`EGS`.
`vl` must be set to the number of `SEW` elements to be processed and
therefore must be a multiple of `EGS=4`. +
Likewise, `vstart` must be a multiple of `EGS=4`

// This instruction requires that `Zvl128b` be implemented (i.e `VLEN>=128`).


NB:: W~13~ is not used by the instruction for producing the next 4 message schedule words.

Note:: Many vector units that are wider than 128 bits may choose to only implement one
128-bit datapath for this instruction. This needs to be transparent to code in terms
of functionality. A vector length setting of wider than 128 bits would require some
sort of instruction expansion.

This instruction is not masked. If any element groups are not to be processed, the _vl_
must be set accordingly.
`VLMUL` must be at least 1. In typical usage it is expected to be 1.
There are three source operands: vd, vs1 and vs2. The result
is written to vd.

In this code the input elements are numbered from 0 (16 words ago) to 15 (most recent message-schedule word).
The outputs are numbered from 16 to 19.

Operation::
[source,pseudocode]
--
function clause execute (VSHA2ms(vs2, vs1, vd)) = {
  // This pseudo code needs to be updated toi support SHA-256 _and_ SHA-512
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
	{W[3],  W[2],  W[1],  W[0]}  : bits(EGW) = get_velem(vd, SEW, i);
    {W[11], W[10], W[9],  W[4]}  : bits(EGW) = get_velem(vs1, SEW, i);
    {W[15], W[14], W[13], W[12]} : bits(EGW) = get_velem(vs2, SEW, i);
  }


  W[16] = sig1(W[14]) + W[9]  + sig0(W[1]) + W[0];
  W[17] = sig1(W[15]) + W[10] + sig0(W[2]) + W[1];
  W[18] = sig1(W[16]) + W[11] + sig0(W[3]) + W[2];
  W[19] = sig1(W[17]) + W[12] + sig0(W[4]) + W[3];

  // This can also be viewed as
  res[0] = sig1(VS2[2]) + VS1[1]  + sig0(Vd[1]) + Vd[0];
  res[1] = sig1(VS2[3]) + VS1[2] + sig0(Vd[2]) + Vd[1];
  res[2] = sig1(res[0])   VS1[3] + sig0(Vd[3]) + Vd[2];
  res[3] = sig1(res[1]) + VS2[0] + sig0(Vs1[0]) + Vd[3];
  vd = {res[3], res[2], res[1], res[0]};

  set_velem(vd, EGW, i, {W[19],W[18],W[17],W[16]});

  RETIRE_SUCCESS
}

// SHA256
function sig0(x) = ROTR(x,7)  XOR ROTR(x,18) XOR SHR(x,3)
function sig1(x) = ROTR(x,17) XOR ROTR(x,19) XOR SHR(x,10)

// SHA512
function sig0(x) = ROTR(x,1)  XOR ROTR(x,8)  XOR SHR(x,7);
function sig1(x) = ROTR(x,19) XOR ROTR(x,61) XOR SHR(x,6);

function ROTR(x,n) = (x >> n) | (x << w - n)
function SHR (x,n) = x >> n

--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvknh>>
| v0.1.0
| In Development
|===