[[insns-vsha2c, Vector SHA-2 Compression]]
= vsha2c[hl].vv

Synopsis::
Vector SHA-2 2 rounds of compression.

Mnemonic::
vsha2ch.vv vd, vs2, vs1 +
vsha2cl.vv vd, vs2, vs1

 NB: We are currently proposing that the two variants of this instruction be 
differentiated by the suffixes h and l.

[NOTE]
.Issue to be resolved soon.
====
We are evaluating if there is an advantage to having two versions of this instruction as opposed to
having one version and using a slideDown or the like between invocations.
====

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| Vd  | input  | 4*SEW  | 4 | SEW | current state {c, d, g, h}
| Vs1 | input  | 4*SEW  | 4 | SEW | MessageSched plus constant[3:0]
| Vs2 | input  | 4*SEW  | 4 | SEW | current state {a, b, e, f}
| Vd  | output | 4*SEW  | 4 | SEW | next state {a, b, e, f}
|===

Description::

- When `SEW`=32, this instruction implements 2 rounds of SHA-256 compression with EGW=128 (`zvknha` and `zvknhb`)
- When `SEW`=64, this instruction implements 2 rounds of SHA-512 compression with EGW=256 (`zvkhnb` only)

If SEW is other than 32 or 64, this instruction takes the illegal instruction exception.

[NOTE]
====
The `vsha2ch` version of this instruction reads the two high words from vs1 while the
`vsha2cl` version only reads the two low words.
Otherwise, these versions of the instruction are identical.
The two forms of the instruction save code from having to swap these two words
if there were just a single instruction.
====

// Many vector units that are wider than 128 bits may choose to only implement one
// 128-bit datapath for this instruction. This needs to be transparent to code in terms
// of functionality. A vector length setting of wider than 128 bits would require some
// sort of instruction expansion.

This instruction is not masked. If any 128-bit element groupss are not to be processed,
the _vl_ must be set accordingly.
VLMUL must be at least 1. In typical usage it is expected to be 1.
There are three source operands: vd, vs1 and vs2. The result
is written to vd.

These instructions take in two SEW words _W1_ and _W0_ which are next two words of the message 
schedule after they have been incremented by the appropriate constant (see
link:https://doi.org/10.6028/NIST.FIPS.180-4[FIPS PUB 180-4 Secure Hash Standard (SHS)])
and eight SEW word variables: _a_, _b_, _c_, _d_, _e_, _f_, _g,_ and _h_. The
output is the new values of _a, b, e_ and _f_ after performing 2 rounds of the hash
computation. The other 4 variables, _c_, _d_, _g_, and _h_, are equal to the input values for _a_, _b_, _e_, _f_ respectively.

These instructions are destructive, where *vd* holds the input values for _c_, _d_,
_g_, and _h_, and after executing two rounds returns the output values of
_a_, _b_, _e_ and _f_.
Thus, the register _specifiers_ for Vd and Vs2 need to be swapped between
instructions. This is done since the input value of _c_, _d_, _g_, and _h_ is no
longer needed. While we could have chosen to have *Vd* hold _a_, _b_, _e_ and _f_ for
the input and the output, this would require code to copy the *Vd* register before
executing one of these instructions so that would be available as input to the next
instruction for the input of _c_, _d_, _g_, and _h_. This would use up one more
vector register and require one more instruction, without any benefit.

These sha two-rounds instructions only require two message schedule words in *Vs1*.
The instruction sha256ra accesses the lower two words, while sha256rb accesses
the upper two words.

[NOTE]
====
It is recommended that implementations have VLEN>=128 for these instructions.
Furthermore, for the best performance in SHA512, it is recommended that implementations have VLEN>=256.
When VLEN<EGW, an appropriate LMUL needs to be used by software so that elements from the 
specified register groups can be combined to form the full element group.
====

[NOTE]
.To reviewers
====
The following pseudo is largely a copy of the pseudo code in FIPS PUB 180-4 Secure Hash Standard (SHS).
We are in the process of updating it including making it work for EGW=128 and EGW=256 
====

Operation::
[source,sail-ish]
--
function clause execute (VSHA2c(vs2, vs1, vd, vv)) = {
// Need to separate based on EGW (128 or 256)

  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
	  let {a, b, e, f} : bits(128) = get_velem(vs2, EGW=128, i);
	  let {c, d, g, h} : bits(128) = get_velem(vd, EGW=128, i);
	  let MessageShedPlusC[3:0] : bits(128) = get_velem(vs1, EGW=128, i);
	  let {W1, W0} == VSHA2cl ? MessageSchedPlusC[1:0] : MessageSchedPlusC[3:2]; // l vs h difference is the words selected

	  T1 = h + sum1(e) + Ch(e,f,g) + W0;
	  T2 = sum0(a) + Maj(a,b,c);
	  h = g;
	  g = f;
	  f = e;	
	  e = d + T1;
	  d = c;
	  c = b;
	  b = a;
	  a = T1 + T2;


	  T1 = h + sum1(e) + Ch(e,f,g) + W1;
	  T2 = sum0(a) + Maj(a,b,c);
	  h = g;
	  g = f;
	  f = e;	
	  e = d + T1;
	  d = c;
	  c = b;
	  b = a;
	  a = T1 + T2;
	  set_velem(vd, EGW=128, i, {f,e,b,a});
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvknh, zvknh[ab]>>
| v0.1.0
| In Development
|===



