[[insns-vsha512ms, Vector SHA-512 Message Schedule]]
= vsha256ms.v

Synopsis::
Vector SHA-512 message schedule.

Mnemonic::
vsha512ms.v vd, vs2, vs1

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OPMVV'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'func3'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=0'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
This instruction takes in a subset of the last 16 message-schedule doublewords and produces the next 4
message-schedule doublewords.

Four 64-bit message schedule doublewords are packed into each `EGW=256` element group of the
source and destination registers 

This instructions takes in 11 of the last 16 64-bit doublewords of the message schedule. The last 16
doublewords of the message schedule are shown here in 256-bit element groups.
The subscripts show the relative age, where W~0~ is the oldest and W~15~ is the most recent
of the 16 doublewords.

`{W~3~, W~2~, W~1~, W~0~} + 
{W~7~, W~6~, W~5~, W~4~} +
{W~11~, W~10~, W~9~, W~8~} +
{W~15~, W~14~, W~13~, W~12~}`

Since W~5~ through W~8~ are not needed in these calculations, we are able to compact these into
three 256-bit element groups

`{W~3~, W~2~, W~1~, W~0~} + 
{W~11~, W~10~, W~9~, W~4~} +
{W~15~, W~14~, W~13~, W~12~}`

[TIP]
.Note to software developers
====
The combining of these 256-bit element groups as shown here can readily be performing using a vector
vmerge instruction with the appropriate mask

`vmerge {W~11~, W~10~, W~9~, W~4~}, {W~11~, W~10~, W~9~, W~8~}, {W~7~, W~6~, W~5~, W~4~}, V0` 


====

The instruction calculates the next 4 64-bit doublewords of the message schedule:

`{W~19~, W~18~, W~17~, W~16~}`

This instruction treats `EEW=64` and `EGS=4`, regardless of `vtype.vsew`
In order to properly specify the number of elements, vl needs to be set to
vl = `vtype.vsew`/128. If vstart is not zero, it needs to be scaled similarly.
This instruction requires that `Zvl256b` be implemented (i.e `VLEN>=256`).


NB:: W~13~ is not used by the instruction for producing the next 4 message schedule doublewords. 

Question:: Should we require W~13~ to reduce the verification space?



Note:: Many vector units that are wider than 128 bits may choose to only implement one
128-bit datapath for this instruction. This needs to be transparent to code in terms
of functionality. A vector length setting of wider than 128 bits would require some
sort of instruction expansion.

This instruction is not masked. If any 128-bit element groups are not to be processed, the _vl_
must be set accordingly.
`VLMUL` must be at least 1. In typical usage it is expected to be 1.
There are three source operands: vd, vs1 and vs2. The result
is written to vd.

In this code the input doublewords are numbered from 0 (16 doublewords ago) to 15 (most recent message-schedule doubleword).
The outputs are numbered from 16 to 19.


Input::
Vd  = {W[3],  W[2],  W[1],  W[0]} +
Vs1 = {W[11], W[10], W[9],  W[4]} +
Vs2 = {W[15], W[14], W[13], W[12]} 

Output::

Vd = {W[19],W[18],W[17],W[16]}

This instruction treats `EEW=64`, regardless of `vtype.vsew` and requires that
 `Zvl256b`be implemented (i.e `VLEN>=256`).

Operation::
[source,pseudocode]
--
function clause execute (VSHA512ms(vs2, vs1, vd)) = {
  assert(VLEN>=256);
	foreach (i from vstart to vl) {
	  {W[3],  W[2],  W[1],  W[0]}  : bits(256) = get_velem(vd, EGW=256, i};
	  {W[11], W[10], W[9],  W[4]}  : bits(256) = get_velem(vs1, EGW=256, i};
	  {W[15], W[14], W[13], W[12]} : bits(256) = get_velem(vs2, EGW=256, i};


 W[16] = sig1(W[14]) + W[9]  + sig0(W[1]) + W[0];
 W[17] = sig1(W[15]) + W[10] + sig0(W[2]) + W[1];
 W[18] = sig1(W[16])   W[11] + sig0(W[3]) + W[2];
 W[19] = sig1(W[17]) + W[12] + sig0(W[4]) + W[3];

 // This can also be viewed as
 res[0] = sig1(VS2[2]) + VS1[1]  + sig0(Vd[1]) + Vd[0];
 res[1] = sig1(VS2[3]) + VS1[2] + sig0(Vd[2]) + Vd[1];
 res[2] = sig1(res[0])   VS1[3] + sig0(Vd[3]) + Vd[2];
 res[3] = sig1(res[1]) + VS2[0] + sig0(Vs1[0]) + Vd[3];
 vd = {res[3].res[2],res[1],res[0]};

	set_velem(vd, EGW=256, i, {W[19],W[18],W[17],W[16]});

 }
  RETIRE_SUCCESS

function sig0(x) = ROTR(x,1)  XOR ROTR(x,8)  XOR SHR(x,7);
function sig1(x) = ROTR(x,19) XOR ROTR(x,61) XOR SHR(x,6);

function ROTR(x,n) = (x >> n) | (x << w - n)
function SHR (x,n) = x >> n
 
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkn2h>>
| v0.1.0
| In Development
|===