[[insns-vsha2c, Vector SHA-2 Compression]]
= vsha2c[hl]

Synopsis::
Vector SHA-2 2 rounds of compression.

Mnemonic::
vsha2ch.vv vd, vs2, vs1 +
vsha2cl.vv vd, vs2, vs1

 NB: We are currently proposing that the two variants of this instruction be 
differentiated by the suffixes h and l. These suffixes --- and indeed the mnemonics
themsleves --- will likely change. Alternatively, we may choose to differentiate
between these two by other means.

Question::
Do we need two versions? Can we have one version and use a slideDown or 
the like without hurting performance?

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm=1'},
{bits: 6, name: 'funct6'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS 
|EEW
|Definition

| Vd  | input  | 4*SEW  | 4 | SEW | {c, d, g, h}
| Vs1 | input  | 4*SEW  | 4 | SEW | MessageSched[3:0]
| Vs2 | input  | 4*SEW  | 4 | SEW | {a, b, e, f}
| Vd  | output | 4*SEW  | 4 | SEW | {a, b, e, f} 
|===
 
Description:: 

- When `SEW`=32, this instruction implements 2 rounds of SHA-256 compression with EGW=128
- When `SEW`=64, this instruction implements 2 rounds of SHA-512 compression with EGW=256

If SEW is other than 32 or 64, this instruction takes the undefined instruction exception.

Note::
The `vsha2ch` version of this instruction reads the two high words from vs1 while the
`vsha2cl` version only reads the two low words.
Otherwise, these versions of the instruction are identical.
The two forms of the instruction save code from having to swap these two words
if there were just a single instruction.

NB: This is very preliminary draft that is being distributed for discussion purposes only. The code is not
executable - it is largely a copy of the pseudo code in FIPS PUB 180-4 Secure Hash Standard (SHS).

// Many vector units that are wider than 128 bits may choose to only implement one
// 128-bit datapath for this instruction. This needs to be transparent to code in terms
// of functionality. A vector length setting of wider than 128 bits would require some
// sort of instruction expansion.

This instruction is not masked. If any 128-bit element groupss are not to be processed,
the _vl_ must be set accordingly.
VLMUL must be at least 1. In typical usage it is expected to be 1.
There are three source operands: vd, vs1 and vs2. The result
is written to vd.

These instructions take in two SEW words of the message schedule _W1_ and _W0_
and eight SEW word variables: _a_, _b_, _c_, _d_, _e_, _f_, _g,_ and _h_. The
output is the new values of _a, b, e_ and _f_ after performing 2 rounds of the hash
computation. The other 4 variables, _c_, _d_, _g_, and _h_, are equal to the input values for _a_, _b_, _e_, _f_ respectively.

These instructions are destructive, where *vd* holds the input values for _c_, _d_,
_g_, and _h_, and after executing two rounds returns the output values of
_a_, _b_, _e_ and _f_.
Thus, the register _specifiers_ for Vd and Vs2 need to be swapped between
instructions. This is done since the input value of _c_, _d_, _g_, and _h_ is no
longer needed. While we could have chosen to have *Vd* hold _a_, _b_, _e_ and _f_ for
the input and the output, this would require code to copy the *Vd* register before
executing one of these instructions so that would be available as input to the next
instruction for the input of _c_, _d_, _g_, and _h_. This would use up one more
vector register and require one more instruction, without any benefit.

These sha two-rounds instructions only require two message schedule words in *Vs1*.
The instruction sha256ra accesses the lower two words, while sha256rb accesses
the upper two words.



Note::
It is recommended that implementations have VLEN>=128 for these instructions.
Furthermore, for the best performance in SHA512, it is recommended that implementations have VLEN>=256.
When VLEN<EGW, an appropriate LMUL needs to be used by software so that elements from the 
specified register groups can be combined to form the full element group.

It is important to note that ELEN>=SEW is a requirement as elements are not
permitted to cross register boundaries.

Operation::
[source,sail-ish]
--
function clause execute (VSHA256Ra(vs2, vs1, vd, vv)) = {
  assert(VLEN>=128);
	foreach (i from vstart to vl) {
	  {f, e, b, a} : bits(128) = get_velem(vs2, EGW=128, i};
	  {h, g, d, c} : bits(128) = get_velem(vd, EGW=128, i};
	  MessageShed[3:0] : bits(128) = get_velem(vs1, EGW=128, i};
	  {W1, W0} == VSHA256Ra ? MessageSched[1:0] : MessageSched[3:2];

	  T1 = h + sum1(e) + Ch(e,f,g) + W0;
	  T2 = sum0(a) + Maj(a,b,c);
	  h = g;
	  g = f;
	  f = e;	
	  e = d + T1;
	  d = c;
	  c = b;
	  b = a;
	  a = T1 + T2;


	  T1 = h + sum1(e) + Ch(e,f,g) + W1;
	  T2 = sum0(a) + Maj(a,b,c);
	  h = g;
	  g = f;
	  f = e;	
	  e = d + T1;
	  d = c;
	  c = b;
	  b = a;
	  a = T1 + T2;
	  set_velem(vd, EGW=128, i, {f,e,b,a);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkn1h>>
| v0.1.0
| In Development
|===



