[[insns-vsha2c, Vector SHA-2 Compression]]
= vsha2c[hl].vv

Synopsis::
Vector SHA-2 2 rounds of compression.

Mnemonic::
vsha2ch.vv vd, vs2, vs1 +
vsha2cl.vv vd, vs2, vs1

[NOTE]
====
Having a high and low version of this instruction will typically improve performance when 
interleaving independent hashing operations (i.e., when hashing several files at once).
The alternative would be to have a single version of the instruction that only operates
on the lower two words of the input which would require additional instructions to slide
the upper two words into the lower two words.
====

Encoding (Vector-Vector) High part::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101110'},
]}
....

Encoding (Vector-Vector) Low part::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101111'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| Vd  | input  | 4*SEW  | 4 | SEW | current state {c, d, g, h}
| Vs1 | input  | 4*SEW  | 4 | SEW | MessageSched plus constant[3:0]
| Vs2 | input  | 4*SEW  | 4 | SEW | current state {a, b, e, f}
| Vd  | output | 4*SEW  | 4 | SEW | next state {a, b, e, f}
|===

Description::
`SEW` must be either 32 or 64, otherwise this instruction encoding is reserved.
- When `SEW`=32, this instruction implements 2 rounds of SHA-256 compression with EGW=128 (`zvknha` and `zvknhb`)
- When `SEW`=64, this instruction implements 2 rounds of SHA-512 compression with EGW=256 (`zvkhnb` only)

[NOTE]
====
The `vsha2ch` version of this instruction reads the two message schedule high words from `vs1` while the
`vsha2cl` version only reads the two message schedule low words.
Otherwise, these versions of the instruction are identical.
The two forms of the instruction save code from having to swap these two words
if there were just a single instruction.
====

This instruction is not masked. If any 128-bit element groups are not to be processed,
the _vl_ must be set accordingly.
VLMUL must be at least 1. In typical usage it is expected to be 1.
There are three source operands: vd, vs1 and vs2. The result
is written to vd.

These instructions take in two SEW words _W1_ and _W0_ which are next two words of the message
schedule after they have been incremented by the appropriate constant (see
link:https://doi.org/10.6028/NIST.FIPS.180-4[FIPS PUB 180-4 Secure Hash Standard (SHS)])
and eight SEW word variables: _a_, _b_, _c_, _d_, _e_, _f_, _g,_ and _h_. The
output is the new values of _a, b, e_ and _f_ after performing 2 rounds of the hash
computation. The other 4 variables, _c_, _d_, _g_, and _h_, are equal to the input values for _a_, _b_, _e_, _f_ respectively.

These instructions are destructive, where *vd* holds the input values for _c_, _d_,
_g_, and _h_, and after executing two rounds returns the output values of
_a_, _b_, _e_ and _f_.
Thus, the register _specifiers_ for Vd and Vs2 need to be swapped between
instructions. This is done since the input value of _c_, _d_, _g_, and _h_ is no
longer needed. While we could have chosen to have *Vd* hold _a_, _b_, _e_ and _f_ for
the input and the output, this would require code to copy the *Vd* register before
executing one of these instructions so that would be available as input to the next
instruction for the input of _c_, _d_, _g_, and _h_. This would use up one more
vector register and require one more instruction, without any benefit.

The case where the `vd` register group overlaps with either `vs1` or `vs2` is _reserved_.

[NOTE]
====
Preventing overlap between `vd` and `vs1` or `vs2` simplifies implementation with `VLEN < EGW`.
This restriction does not have any coding impact since proper implementation of the algorithm requires
that `vd`, `vs1` and `vs2` each are different registers.
====

[NOTE]
====
It is recommended that implementations have VLEN>=128 for these instructions.
Furthermore, for the best performance in SHA512, it is recommended that implementations have VLEN>=256.
When VLEN<EGW, an appropriate LMUL needs to be used by software so that elements from the 
specified register groups can be combined to form the full element group.
====

The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `SEW=32` elements to be processed and
therefore must be a multiple of `EGS=4`. +
Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,sail]
--
function clause execute (VSHA2c(vs2, vs1, vd)) = {

  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
	  let {a, b, e, f} : bits(4*SEW) = get_velem(vs2, 4*SEW, i);
	  let {c, d, g, h} : bits(4*SEW) = get_velem(vd, 4*SEW, i);
	  let MessageShedPlusC[3:0] : bits(4*SEW) = get_velem(vs1, 4*SEW, i);
	  let {W1, W0} == VSHA2cl ? MessageSchedPlusC[1:0] : MessageSchedPlusC[3:2]; // l vs h difference is the words selected

	  let T1 : bits(SEW) = h + sum1(e) + ch(e,f,g) + W0;
	  let T2 : bits(SEW) = sum0(a) + maj(a,b,c);
	  h  = g;
	  g  = f;
	  f  = e;	
	  e  = d + T1;
	  d  = c;
	  c  = b;
	  b  = a;
	  a  = T1 + T2;


	  T1  = h + sum1(e) + ch(e,f,g) + W1;
	  T2  = sum0(a) + maj(a,b,c);
	  h = g;
	  g = f;
	  f = e;	
	  e = d + T1;
	  d = c;
	  c = b;
	  b = a;
	  a = T1 + T2;
	  set_velem(vd, 4*SEW, i, {f,e,b,a});
  }
  RETIRE_SUCCESS
}

function sum0(x) = {
	match SEW {
		32 => rotr(x,2)  XOR rotr(x,13) XOR rotr(x,22),
		64 => rotr(x,28) XOR rotr(x,34) XOR rotr(x,39)
	}
}

function sum1(x) = {
	match SEW {
		32 => rotr(x,6)  XOR rotr(x,11) XOR rotr(x,25),
		64 => rotr(x,14) XOR rotr(x,18) XOR rotr(x,41)
	}
}

function ch(x, y, z) = ((x & y) ^ ((~x) & z))


function maj(x, y, z) =  ((x & y) ^ (x & z) ^ (y & z))

function ROTR(x,n) = (x >> n) | (x << SEW - n)

--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvknh, zvknh[ab]>>
| v0.1.0
| In Development
|===



