[[insns-vsha512c, Vector SHA-512 Compression]]
= vsha512c[ab].v

Synopsis::
Vector SHA-512 2 rounds of compression. EGW=256

Mnemonic::
vsha512ca.v vd, vs2, vs1 +
vsha512cb.v vd, vs2, vs1

 NB: We are currently proposing that the two variants of this instruction be 
differentiated by the suffixes a and b. These suffixes --- and indeed the mnemonics
themsleves --- will likely change. Alternatively, we may choose to differentiate
between these two by other means.

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OPMVV'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'func3'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
NB: This is very preliminary draft that is being distributed for discussion purposes only. The code is not
executable - it is largely a copy of the pseudo code in FIPS PUB 180-4 Secure Hash Standard (SHS).

This instruction has an EEW=256, that is, it operates on 256-bit element groups.
It is not directly impacted by VSEW

 Many vector units that are wider than 256 bits may choose to only implement one
256-bit datapath for this instruction. This needs to be transparent to code in terms
of functionality. A vector length setting of wider than 256 bits would require some
sort of instruction expansion.

This instruction is not masked. If any 256-bit elements are not processed, the _vl_
must be set accordingly.
VLMUL must be at least 1. In typical usage it is expected to be 1.
There are three source operands: vd, vs1 and vs2. The result
is written to vd.

The two forms of this instruction are identical except one form (vsha512ra) uses the
two least significant doublewords of vs1 input, while vsha512rb uses the 
two most significant doublewords. This is described in pseduo-code below in a manner
that should be _temporarily_ suitable for expository purposes.
The two forms of the instruction save code from having to swap these two words
if there were just a single instruction.

These instructions take in two 64-bit words of the message schedule _W1_ and _W0_
and eight 64-bit word variables: _a_, _b_, _c_, _d_, _e_, _f_, _g,_ and _h_. The
output is the new values of _a, b, e_ and _f_ after performing 2 rounds of the hash
computation. The other 4 variables, _c_, _d_, _g_, and _h_, are equal to the input values for _a_, _b_, _e_, _f_ respectively.

These instructions are destructive, where *vd* holds the input values for _c_, _d_,
_g_, and _h_, and after executing two rounds returns the output values of
_a_, _b_, _e_ and _f_.
Thus, the register _specifiers_ for Vd and Vs2 need to be swapped between
instructions. This is done since the input value of _c_, _d_, _g_, and _h_ is no
longer needed. While we could have chosen to have *Vd* hold _a_, _b_, _e_ and _f_ for
the input and the output, this would require code to copy the *Vd* register before
executing one of these instructions so that would be available as input to the next
instruction for the input of _c_, _d_, _g_, and _h_. This would use up one more
vector register and require one more instruction, without any benefit.

These sha two-rounds instructions only require two message schedule words in *Vs1*.
The instruction sha512ra accesses the lower two words, while sha512rb accesses
the upper two words.

 Input:
  Vd  = {h, g, d, c}
  Vs2 = {f, e, b, a}
  Vs1 = {-, -, MessageSched[1:0]} // for vsha512ra
  Vs1 = {MessageSched[3:2], -, -} // for vsha512rb
 
 Output:
  vd = {a, b, e, f}

This instruction treats `EGW=256`, regardless of `vtype.vsew` and requires that
 `Zvl256b`be implemented (i.e `VLEN>=256`).

Operation::
[source,sail-ish]
--
function clause execute (VSHA512c(vs2, vs1, vd, vv)) = {
  assert(VLEN>=256);
	foreach (i from vlstart to vl) {
	  {f, e, b, a} : bits(256) = get_velem(vs2, EGW=256, i};
	  {h, g, d, c} : bits(256) = get_velem(vd, EGW=256, i};
	  MessageShed[3:0] : bits(256) = get_velem(vs1, EGW=256, i};
	  {W1, W0} == VSHA256Ra ? MessageSched[1:0] : MessageSched[3:2];

	  T1 = h + sum1(e) + Ch(e,f,g) + W0;
	  T2 = sum0(a) + Maj(a,b,c);
	  h = g;
	  g = f;
	  f = e;	
	  e = d + T1;
	  d = c;
	  c = b;
	  b = a;
	  a = T1 + T2;


	  T1 = h + sum1(e) + Ch(e,f,g) + W1;
	  T2 = sum0(a) + Maj(a,b,c);
	  h = g;
	  g = f;
	  f = e;	
	  e = d + T1;
	  d = c;
	  c = b;
	  b = a;
	  a = T1 + T2;
	  set_velem(vd, EGW=256, i, {f,e,b,a);
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvknh2>>
| v0.1.0
| In Development
|===



