[[insns-vsm3me, SM3 Message Expansion]]
= vsm3me.vv

Synopsis::
Vector SM3 Message Expansion - 8 rounds per instruction

Mnemonic::
vsm3me.vv vd, vs2, vs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '100000'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| Vs1 | input  | 256  | 8 | 32 | Message words W[0:7]
| Vs2 | input  | 256  | 8 | 32 | Message words W[8:15]
| Vd  | output | 256  | 8 | 32 | Message words W[16:23]
|===

Description::
This instruction implements 8 rounds of SM3 message expansion,  producing eight 32-bit
outputs in a 256-bit 8-element group.
It treats each 256-bit 8-element group of `vs1` and `vs2` as the data input.


This instruction treats `EEW=32` and `EGS=8`, regardless of `vtype.vsew`
`vl` needs to be set to eight times the number of element groups.
If vstart is not zero, it needs to be scaled similarly.
// This instruction requires that `Zvl256b` be implemented (i.e `VLEN>=256`).

[NOTE]
====
For the best performance, it is recommended that implementations have VLEN>=256.
When VLEN<EGW, an appropriate LMUL needs to be used by software so that elements from the 
specified register groups can be combined to form the full element group.
====


Operation::
[source,sail]
--
function clause execute (VSM3ME(vs2, vs1)) = {
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
    let (w0, w1, w2, w3, w4, w5, w6, w7)= \
       : bits(256) = get_velem(vs1, 256, i);
    let (w8,  w9, w10, w11, w12, w13, w14, w15)
       : bits(256) = get_velem(vs2, 256, i);

    // Arguments are W[i-16], W[i-9], W[i-13], W[i-6].
    // Note that some of the newly computed words are used in later invocations.
    let w16 = ZVKSH_W(w0,  w7, w13,  w3, w10);
    let w17 = ZVKSH_W(w1,  w8, w14,  w4, w11);
    let w18 = ZVKSH_W(w2,  w9, w15,  w5, w12);
    let w19 = ZVKSH_W(w3, w10, w16,  w6, w13);
    let w20 = ZVKSH_W(w4, w11, w17,  w7, w14);
    let w21 = ZVKSH_W(w5, w12, w18,  w8, w15);
    let w22 = ZVKSH_W(w6, w13, w19,  w9, w16);
    let w23 = ZVKSH_W(w7, w14, w20, w10, w17);

    // Update the destination register.
    SET_EGU32x8_LE(vd, w16, w17, w18, w19, w20, w21, w22, w23);
  }
  RETIRE_SUCCESS
}

  function P_1(X) ((X) ^ ROL32((X), 15) ^ ROL32((X), 23))

  function ZVKSH_W(M16, M9, M3, M13, M6) = \
  (P1( (M16) ^  (M9) ^ ROL32((M3), 15) ) ^ ROL32((M13), 7) ^ (M6))
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvksh>>
| v0.1.0
| In Development
|===
