[[insns-vsm3c, SM3 Compression]]
= vsm3c.vi

Synopsis::
Vector SM3 Compression

Mnemonic::
vsm3r.vi vd, vs2, rnd

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVI'},
{bits: 5, name: 'rnd'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: 'funct6'},
]}
....

Description:: 
Performs 2 rounds of SM3 Compression, producing eight 32-bit outputs in
a 256-bit 8-element group.

The immediate field `rnd` has only two valid values: 0 and 1; all other values are reserved.
A 'rnd' value of 0 is used for rounds 0-15, and 1 is used for rounds 16-63.

It treats each 256-bit 8-element group of `vd` as eight 32-bit words,  
and each 256-bit 8-element group of `vs2` as eight 32-bit words. Only 4 of these words are consumed by
this instruction, the rest are don't-cares.

vs1 = {w[j], w[j+1], w[j+2], w[j+3], w[j+4], w[j+5], w[j+6], w[j+7]}

The values consumed by the instruction are

vs1 = {w[j], w[j+1], -, -, w[j+4], w[j+5], -, -}

Where the "-" characters are not consumed and are therefore don't cares.

This instruction consumes the "W" message schedule inputs and internally generates the "W'" values as needed



// NB::
// It probably makes sense to have vs1 and vs2 hold eight 32-bit words each and have 4 versions of this instruction;
// one for each pair of inputs.
// This fits more naturally with the generating instructions and doesn't leave us with the oddity of 64-bit and 256-bit element groups
// Vd (in) = {A,B,C,D,E,F,G,H} 
// vs1 = W[0:7]  // 8 expanded words
// vs2 = W’[0:7] // 8 expanded words with XORing
// Vd (out) = {A,B,C,D,E,F,G,H} 




This instruction treats `EEW=32` regardless of `vtype.vsew`
`vl` needs to be set to eight times the number of element groups.
If vstart is not zero, it needs to be scaled similarly.
This instruction requires that `Zvl128b` be implemented (i.e `VLEN>=128`).

Operation::
[source,pseudocode]
--
function clause execute (VAESESFK1(rnd, vs2)) = {
  assert(VLEN>=256);
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS
  // assert round key in range

  elementgroups = (vl/EGS)
  egstart = (vstart/EGS)
  vlen = vl/EGS
  
  
// your code goes here
 SS1 <- ROTL7((ROTL12(A) + E + (ROTLjmod32(T_j))
  SS2 <- SS1 xor ROTL12(A)
  TT1 <- FF_j(A, B, C) + D + SS2 + W'[i]
  TT2 <- GG_j(E, F, G) + H + SS1 + W[i]
  D <- C0
  C1 <- ROTL9(B)
  B <- A0
  A1 <- TT1
  H <- G0
  G1 <- ROTL19(F)
  F <- E0
  E1 <- P_0(TT2)

  SS1 <- ROTL7((ROTL12(A1) + E1 + (ROTLjmod32(T_j))
  SS2 <- SS1 xor ROTL12(A1)
  TT1 <- FF_j(A1, A0, C1) + C0 + SS2 + W'[i+1]
  TT2 <- GG_j(E1, E0, G1) + G0 + SS1 + W[i+1]
  D <- C1
  C2 <- ROTL9(A0)
  B <- A1
  A2 <- TT1
  H <- G1
  G2 <- ROTL19(E0)
  F <- E1
  E2 <- P_0(TT2)

Output: {A2, A1, C2, C1, E2, E1, G2, G1}


  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvkssh>>
| v0.1.0
| In Development
|===