[[insns-vsm4k, Vector SM4 Key Expansion]]
= vsm4k.vi

Synopsis::
Vector SM4 KeyExpansion

Mnemonic::
vsm4k.vi vd, vs2, uimm

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: 'rnd'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '100001'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|EEW
|Definition

| uimm | input  | -    | - | -  | Round group (rnd)
| Vs2  | input  | 128  | 4 | 32 | Current 4 round keys rK[0:3]
| Vd   | output | 128  | 4 | 32 | Next 4 round keys rK'[0:3]
|===

Description::
This instruction implements 4 rounds of the SM4 Key Expansion, producing four 32-bit round keys
as defined in SM4 (see
link:https://www.rfc-editor.org/rfc/rfc8998.html[RFC 8998 ShangMi (SM) Cipher Suites for TLS 1.3]).
It treats each 128-bit element group of `vs2` as the last four round keys.
The rounds number is stored in the unsigned 5-bit `rnd` immediate. Legal values are 0 - 7 and indicate which
group of four rounds are being generated. For example, if `rnd`=1, then round keys 4, 5, 6, and 7 are
being generated.
Out of range values are reserved.

  
  vs2 = {rK[i-4], rK[i-3],rK[i-2], rK[i-1]} // last 4 round keys +
  imm = 0 to 7; // group of 4 rounds +
  vd (out) = {rK[i], rK[i+1],rK[i+2], rK[i+3]} // next 4 rounds keys +

Each of the 32 rounds consumes the last 4 32-bit keys along with a round constant and produces the next 32-bit key.


[NOTE]
====
The initial input to the round key generation is produced by XORing the 128-bit encryption key with a so-called system parameter: FK[3:0]
====

////
.System Parameters
[%autowidth]
[%header,cols="^2,^2"]
|===
|FK
|constant

| 0 | A3B1BAC6
| 1 | 56AA3350 
| 2 | 677D9197
| 3 | B27022DC
|===
////

  MK = {MK[0], MK[1], MK[2], MK[3]} // Encryption Key
  rK[-4,-1] = K[0:3] = MK[0:3] ^ FK[0:3]


The round keys are rK[0] to rK[31]
  B = (rK[i-3] &#8853; rK[i-2] &#8853; rK[i-1] &#8853; CK[round]); +
  S = subBytes(B); + 
  rK[i]= rK[i-4] &#8853; S &#8853; ROTL13(S) &#8853; ROTR23(S); +

The round constants and the S-box are described below and can be found at https://datatracker.ietf.org/doc/id/draft-crypto-sm4-00

[NOTE]
====
The round constants can be generated on the fly fairly cheaply.
If the bytes of the constants are assigned an incrementing index from 0 to 127, the value of each byte is equal to its index multiplied by 7 modulo 256.
Since the results are all limited to 8 bits, the modulo operation occurs for free:

	B[n] = n + 2n + 4n;
       = 8n + ~n + 1;
====

This instruction only returns the generated keys to the same element group as the source.
If it is desired to have the same key in all vector groups, either the input vector groups
need to contain the same values, or the output from a particular group needs to be "broadcast"
to the other groups using an instruction such as vrgather.

This instruction treats `EEW=32` and `EGS=4`, regardless of `vtype.vsew`
`vl` needs to be set to four times the number of element groups.
If vstart is not zero, it needs to be scaled similarly.

Operation::
[source,sail]
--

function clause execute (vsm4k(rnd, vs2)) = {
  assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
    let (rk0, rk1, rk2, rk3) : bits(128) = get_velem(vs2, 128, i);
    
    let B : bits(32) = rk1 ^ rk2 ^ rk3 ^ CK(4 * rnd);
    let S : bits(32) = SUB_BYTES_SM4(B);
    let rk4 : bits(32) = ROUND_KEY(rk0, S);

    B = rk2 ^ rk3 ^ rk4 ^ CK(4 * round + 1);
    S = SUB_BYTES_SM4(B);
    let rk5 : bits(32) = ROUND_KEY(rk1, S);

    B = rk3 ^ rk4 ^ rk5 ^ CK(4 * round + 2);
    S = SUB_BYTES_SM4(B);
    let rk6 : bits(32) = ROUND_KEY(rk2, S);

    B = rk4 ^ rk5 ^ rk6 ^ CK(4 * round + 3);
    S = SUB_BYTES_SM4(B);
    let rk7 : bits(32) = ROUND_KEY(rk3, S);

    // Update the destination register.
   set_velem(vd, EGW=128, i, (rk4, rk5, rk6, rk7));
  }
  RETIRE_SUCCESS
}

function ROUND_KEY(X, S) = ((X) ^ ((S) ^ ROL32((S), 13) ^ ROL32((S), 23)))

function CK(BYTE) = (ck[(BYTE)])
function SBOX(BYTE)  = (sm4_sbox[(BYTE)])

function SUB_BYTES_SM4(B) = \
  (SBOX(B, 0)) @ SBOX(B, 1) @ SBOX(B, 2) @ SBOX((B, 3))

function ROL32(x,n) = (X << N) | (X >> (32 - N))

sm4_sbox[256] = {
	0xD6, 0x90, 0xE9, 0xFE, 0xCC, 0xE1, 0x3D, 0xB7, 0x16, 0xB6, 0x14, 0xC2,
	0x28, 0xFB, 0x2C, 0x05, 0x2B, 0x67, 0x9A, 0x76, 0x2A, 0xBE, 0x04, 0xC3,
	0xAA, 0x44, 0x13, 0x26, 0x49, 0x86, 0x06, 0x99, 0x9C, 0x42, 0x50, 0xF4,
	0x91, 0xEF, 0x98, 0x7A, 0x33, 0x54, 0x0B, 0x43, 0xED, 0xCF, 0xAC, 0x62,
	0xE4, 0xB3, 0x1C, 0xA9, 0xC9, 0x08, 0xE8, 0x95, 0x80, 0xDF, 0x94, 0xFA,
	0x75, 0x8F, 0x3F, 0xA6, 0x47, 0x07, 0xA7, 0xFC, 0xF3, 0x73, 0x17, 0xBA,
	0x83, 0x59, 0x3C, 0x19, 0xE6, 0x85, 0x4F, 0xA8, 0x68, 0x6B, 0x81, 0xB2,
	0x71, 0x64, 0xDA, 0x8B, 0xF8, 0xEB, 0x0F, 0x4B, 0x70, 0x56, 0x9D, 0x35,
	0x1E, 0x24, 0x0E, 0x5E, 0x63, 0x58, 0xD1, 0xA2, 0x25, 0x22, 0x7C, 0x3B,
	0x01, 0x21, 0x78, 0x87, 0xD4, 0x00, 0x46, 0x57, 0x9F, 0xD3, 0x27, 0x52,
	0x4C, 0x36, 0x02, 0xE7, 0xA0, 0xC4, 0xC8, 0x9E, 0xEA, 0xBF, 0x8A, 0xD2,
	0x40, 0xC7, 0x38, 0xB5, 0xA3, 0xF7, 0xF2, 0xCE, 0xF9, 0x61, 0x15, 0xA1,
	0xE0, 0xAE, 0x5D, 0xA4, 0x9B, 0x34, 0x1A, 0x55, 0xAD, 0x93, 0x32, 0x30,
	0xF5, 0x8C, 0xB1, 0xE3, 0x1D, 0xF6, 0xE2, 0x2E, 0x82, 0x66, 0xCA, 0x60,
	0xC0, 0x29, 0x23, 0xAB, 0x0D, 0x53, 0x4E, 0x6F, 0xD5, 0xDB, 0x37, 0x45,
	0xDE, 0xFD, 0x8E, 0x2F, 0x03, 0xFF, 0x6A, 0x72, 0x6D, 0x6C, 0x5B, 0x51,
	0x8D, 0x1B, 0xAF, 0x92, 0xBB, 0xDD, 0xBC, 0x7F, 0x11, 0xD9, 0x5C, 0x41,
	0x1F, 0x10, 0x5A, 0xD8, 0x0A, 0xC1, 0x31, 0x88, 0xA5, 0xCD, 0x7B, 0xBD,
	0x2D, 0x74, 0xD0, 0x12, 0xB8, 0xE5, 0xB4, 0xB0, 0x89, 0x69, 0x97, 0x4A,
	0x0C, 0x96, 0x77, 0x7E, 0x65, 0xB9, 0xF1, 0x09, 0xC5, 0x6E, 0xC6, 0x84,
	0x18, 0xF0, 0x7D, 0xEC, 0x3A, 0xDC, 0x4D, 0x20, 0x79, 0xEE, 0x5F, 0x3E,
	0xD7, 0xCB, 0x39, 0x48
};

// SM4 Constant Key (CK) - section 7.3.2. of the IETF draft.
ck[32] = {
	0x00070E15, 0x1C232A31, 0x383F464D, 0x545B6269,
	0x70777E85, 0x8C939AA1, 0xA8AFB6BD, 0xC4CBD2D9,
	0xE0E7EEF5, 0xFC030A11, 0x181F262D, 0x343B4249,
	0x50575E65, 0x6C737A81, 0x888F969D, 0xA4ABB2B9,
	0xC0C7CED5, 0xDCE3EAF1, 0xF8FF060D, 0x141B2229,
	0x30373E45, 0x4C535A61, 0x686F767D, 0x848B9299,
	0xA0A7AEB5, 0xBCC3CAD1, 0xD8DFE6ED, 0xF4FB0209,
	0x10171E25, 0x2C333A41, 0x484F565D, 0x646B7279
};


--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvksed>>
| v0.1.0
| In Development
|===
