[[insns-vsm4r, SM4 Rounds]]
= vsm4r.[vv,vs]

Synopsis::
Vector SM4 Rounds

Mnemonic::
vsm4r.vv vd, vs2 +
vsm4r.vs vd, vs2

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '10000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '10000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101001'},
]}
....
Reserved Encodings::
* `SEW` is any value other than 32
* Only for the `.vs` form: the `vd` register group overlaps the `vs2` register

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|SEW
|Definition

| Vd   | input  | 128  | 4 | 32 | Current state X[0:3]
| Vs2  | input  | 128  | 4 | 32 | Current 4 round keys rk[0:3]
| Vd   | output | 128  | 4 | 32 | Next state X'[0:3]
|===

Description::
This instruction implements 4 rounds of SM4 Encryption/Decryption.

It  produces four 32-bit outputs in a 128-bit 4-element group.
It treats each 128-bit 4-element group of `vd` as the state data input.
The `.vv` form treats each 128-bit 4-element group of `vs2` as the four round keys and

In the case of the `.vs` form of the instruction, the element group 0 of the single register `vs2` holds a single element group that is used as the round key for all of the element groups in register group `vd`.

vd (in) = {x[i-4], X[i-3]. X[i-2], X[i-1]} +
vs2 = {rk[i-4],rk[i-3], rk[i-2], rk[i-1]} +
vd (out) = {x[i], X[i+1], X[i+2], X[i+3]} +

For example, if i=4 +
vd (in) = {x[0], X[1], X[2], X[3]} +
vs2 = {rk[0],rk[1], rk[2], rk[3]} +
vd (out) = {x[4], X[5], X[6], X[7]} +

A draft of the SM4 standard is available at: https://datatracker.ietf.org/doc/id/draft-crypto-sm4-00

[NOTE]
====
In SM4, encryption and decryption are identical except that decryption consumes the round keys in the reverse order.
====

Each round is produced by the following +
  B = (X[i-3] &#8853; X[i-2] &#8853; X[i-1] &#8853; rk[i-4]) +
  S = subBytes(B); 1 s-box per byte +
  X[i]= X[i-4] &#8853; S &#8853; ROL2(S) &#8853; ROL10(S) &#8853; ROL18(S) &#8853; ROL24(S) +

Each of the 32 rounds consumes the last 4 32-bit outputs with a round key and produces the next 32-bit output.

NB: The rounds start with i=4 as {X[3],x[2],X[1],X[0]} is the initial data input to the round function
and rk[0] is the initial round key.

The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `SEW=32` elements to be processed and
therefore must be a multiple of `EGS=4`. +
Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,pseudocode]
--
function clause execute (VSM4R(vd, vs2)) = {
  assert((vl%EGS)<>0)     // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
 let B  : bits(32) = 0;
 let S  : bits(32) = 0;
 let rk0 : bits(32) = 0;
 let rk1 : bits(32) = 0;
 let rk2 : bits(32) = 0;
 let rk3 : bits(32) = 0;
 let x0 : bits(32) = 0;
 let x1 : bits(32) = 0;
 let x2 : bits(32) = 0;
 let x3 : bits(32) = 0;
 let x4 : bits(32) = 0;
 let x5 : bits(32) = 0;
 let x6 : bits(32) = 0;
 let x7 : bits(32) = 0;

 let keyelem : bits(32) = 0;

  foreach (i from eg_start to eg_len-1) {
    keyelem = if suffix == "vv" then i else 0;
    {rk0, rk1, rk2, rk3} : bits(128) = get_velem(vs2, EGW=128, keyelem);
    {x0, x1, x2, x3} : bits(128) = get_velem(vd, EGW=128, i);

    B  = x1 ^ x2 ^ x3 ^ rk0;
    S = sm4_subword(B);
    x4 = sm4_round(x0, S);

    B = x2 ^ x3 ^ x4 ^ rk1;
    S = sm4_subword(B);
    x5= sm4_round(x1, S);

    B = x3 ^ x4 ^ x5 ^ rk2;
    S = sm4_subword(B);
    x6 = sm4_round(x2, S);

    B = x4 ^ x5 ^ x6 ^ rk3;
    S = sm4_subword(B);
    x7 = sm4_round(x3, S);

    set_velem(vd, EGW=128, i, x4, x5, x6, x7);

  }
  RETIRE_SUCCESS
}

val sm4_round : bits(32) -> bits(32)
function sm4_round(X, S) = \
  ((X) ^ ((S) ^ ROL32((S), 2) ^ ROL32((S), 10) ^ ROL32((S), 18) ^ ROL32((S), 24)))

--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvksed>>
| v0.1.0
| In Development
|===
