[[insns-vsm4r, SM4 Rounds]]
= vsm4r.vv

Synopsis::
Vector SM4 Rounds

Mnemonic::
vsm4r.vv vd, vs2

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-P'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPMVV'},
{bits: 5, name: '10000'},
{bits: 5, name: 'vs2'},
{bits: 1, name: '1'},
{bits: 6, name: '101000'},
]}
....

Arguments::

[%autowidth]
[%header,cols="4,2,2,2,2,2"]
|===
|Register
|Direction
|EGW
|EGS
|SEW
|Definition

| Vd   | input  | 128  | 4 | 32 | Current state X[0:3]
| Vs2  | input  | 128  | 4 | 32 | Current 4 round keys rk[0:3]
| Vd   | output | 128  | 4 | 32 | Next state X'[0:3]
|===

Description::
`SEW` must be 32, otherwise the instruction encoding is reserved.

This instruction implements 4 rounds of SM4 Encryption/Decryption, producing four 32-bit outputs in
a 128-bit 4-element group.
It treats each 128-bit 4-element group of `vs2` as the four round keys and
each 128-bit 4-element group of `vs2` as the data input.

vd (in) = {x[i-4], X[i-3]. X[i-2], X[i-1]} +
vs2 = {rk[i-4],rk[i-3], rk[i-2], rk[i-1]} +
vd (out) = {x[i], X[i+1], X[i+2], X[i+3]} +

For example, if i=4 +
vd (in) = {x[0], X[1], X[2], X[3]} +
vs2 = {rk[0],rk[1], rk[2], rk[3]} +
vd (out) = {x[4], X[5], X[6], X[7]} +

The SM4 standard is available at: https://datatracker.ietf.org/doc/id/draft-crypto-sm4-00

[NOTE]
====
In SM4, encryption and decryption are identical except that decryption consumes the round keys in the reverse order.
====

Each round is produced by the following +
  B = (X[i-3] &#8853; X[i-2] &#8853; X[i-1] &#8853; rk[i-4]) +
  S = subBytes(B); 1 s-box per byte +
  X[i]= X[i-4] &#8853; S &#8853; ROL2(S) &#8853; ROL10(S) &#8853; ROL18(S) &#8853; ROL24(S) +

Each of the 32 rounds consumes the last 4 32-bit outputs with a round key and produces the next 32-bit output.

NB: The rounds start with i=4 as {X[3],x[2],X[1],X[0]} is the initial data input to the round function
and rk[0] is the initial round key.

The number of element groups to be processed is `vl`/`EGS`.
`vl` must be set to the number of `SEW=32` elements to be processed and
therefore must be a multiple of `EGS=4`. +
Likewise, `vstart` must be a multiple of `EGS=4`.

Operation::
[source,pseudocode]
--
function clause execute (VSM4R(vd, vs2)) = {
   assert((vl%EGS)<>0)       // vl must be a multiple of EGS
  assert((vstart%EGS)<>0) //  vstart must be a multiple of EGS

  eg_len = (vl/EGS)
  eg_start = (vstart/EGS)
  
  foreach (i from eg_start to eg_len-1) {
    let (rk0, rk1, rk2, rk3) : bits(128) = get_velem(vs2, EGW=128, i);
    let (X0, X1, X2, X3) : bits(128) = get_velem(vd, EGW=128, i);

    // 1st round
    B = (X1 ^ X2 ^ X3 ^ rk0)
    S = sm4_subword(B); 1 s-box per byte
    let Y0 : bits(32) = X0 ^ S ^ ROL(S,2)^ ROL(S,10)^ ROL(S,18) ^ ROL(S,24)
    // 2nd round
    B = (X2 ^ X3 ^ X4 ^ rk1)
    S = sm4_subword(B); 1 s-box per byte
    Y1= X1 ^ S ^ ROL(S,2)^ ROL(S,10)^ ROL(S,18) ^ ROL(S,24)
    //3rd round
    B = (X3 ^ Y0 ^ X1 ^ rk2)
    S = sm4_subword(B); 1 s-box per byte
    Y2= X2 ^ S ^ ROL(S,2)^ ROL(S,10)^ ROL(S,18) ^ ROL(S,24)
    //4th round
    B = (Y0 ^ Y1 ^ Y2 ^ rk3)
    S = sm4_subword(B); 1 s-box per byte
    Y3= X3 ^ S ^ ROL(S,2)^ ROL(S,10)^ ROL(S,18) ^ ROL(S,24)
    set_velem(vd, EGW=128, i, (Y0, Y1, Y2, Y3));
  }
  RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvksed>>
| v0.1.0
| In Development
|===
