[[crypto-vector-element-groups]]
=== Crypto Vector Element Groups

Many vector crypto instructions operate on larger operands than instructions in the base vector extension. Typically, these operands are 128- and 256-bits wide. In many cases, these operands are comprised of smaller elements that are combined. However, in other cases these operands are a single value. For example, AES operates on 128-bit blocks comprised of four 32-bit words using 128-bit round keys that are generated from 128-, 192-, and 256-bit cipher keys.

In order to be compatible with the 32- and 64-bit element widths of the base vector instructions,
we treat these operands as a vector of one of more element groups (see 
link:https://github.com/riscv/riscv-v-spec/blob/master/element_groups.adoc[RISC-V Vector Element Groups]).

An element group is defined by three parameters, all of which are explicitly defined by each crypto instruction
that operates on them:

- Element Group Width (EGW) - total number of bits in an element group
- Element Group Size (EGS) - number of elements in an element group
- Effective Element Width (EEW) - number of bits in each element

When the EEW is explicitly defined for a vector crypto instruction, the current `SEW` is ignored by that instruction.

As with all vector instructions, the number of elements processed by a vector instruction is specified by the
vector length `vl`. The number of element groups operated upon is then `vl`/`EGS`.
Attempting to execute a Vector Crypto Instruction when this this ratio is not an
integral value will result in an illegal instruction exception.

Since `vstart` is expressed in elements, the starting element group is `vstart`/`EGS`. 
Attempting to execute a Vector Crypto Instruction when this this ratio is not an
integral value will result in an illegal instruction exception.

For the best performance, it is suggested that Vector Crypto instructions be implemented in
vector units that have `VLEN` that is at least as wide as each instruction's `EGW`.
Element groups can be formed
across registers in implementations where `VLEN`< `EGW` by using an `LMUL`>1. 
However, attempting to execute an instruction where `VLEN`< `EEW` will result in an illegal
instruction exception.

// The Vector Crypto instructions that operate on element groups each have a minimum `VLEN` that is equal
// to the `EGW`. An attempt to execute an instruction with `VLEN`<`EGW` will cause an illegal
// instruction exception to be raised. 

Systems which implement `VLEN` < `EGW` should consider the existing
Scalar Cryptography Extensions, specifically <<Zkne,Zkne>> and <<Zknd,Zknd>>
for accelerated cryptographic operations.

[%header,cols="4,4,4,4,4"]
|===
| Instruction Group
| Extension
| EGW
| EEW
| EGS

| AES      | <<zvkns>>, <<zvknf>> | 128 | 32 | 4
| SHA256   | <<zvknha>>           | 128 | 32 | 4
| SHA512   | <<zvknhb>>           | 256 | 64 | 4
| GCM      | <<zvkgb>>            | 128 | 32 | 4
| SM4      | <<zvksed>>           | 128 | 32 | 4
| SM3      | <<Zvksh>>            | 256 | 32 | 8
|===

NB: Some of the new vector crypto instructions use SEW as usual. For example: rotate, CLMUL  
