[[zvknh, zvknh[ab]]]
=== `Zvknh[ab]` - NIST Suite: Vector SHA-2

Instructions for accelerating SHA-2

`SEW` differentiates between SHA-256 (`SEW`=32) and SHA-512 (`SEW`=64). 

To help avoid side-channel timing attacks, these instructions shall be implemented with data-independent timing.

[%header,cols="^2,^2,^2,^2"]
|===
|SEW
|EGW
|SHA-2
|Extension

|32 | 128 | SHA-256 | Zvknha, Zvknhb
|64 | 256 | SHA-512 | Zvknhb
|===

[NOTE]
====
If Zvknhb is implemented, `SEW` is used to differentiate between SHA-256 (SEW=32) and SHA-512 (SEW=64).
If Zvknha is implemented, only SHA-256 is supported, and SEW must be 32.
====

For SHA-256, implementations with VLEN < 128 require software to use LMUL>1 to combine
32-bit elements from register groups to provide all four elements of the element group.

For SHA-512, implementations with VLEN < 256 require software to use LMUL>1 to combine
64-bit elements from register groups to provide all four elements of the element group.

[%header,cols="^2,4"]
|===
// |`VLENmin`
|Mnemonic
|Instruction

// | 128
| vsha2ms.vv   | <<insns-vsha2ms>>
// | 128
| vsha2c[hl].vv    | <<insns-vsha2c>>
|===

