[[crypto-vector-instruction-constraints]]
=== Crypto Vector Instructions Constraints
The following is a quick reference for the various constraints of specific Vector Crytpo instructions.

vl and vstart constraints::
Since `vl` and `vstart` refer to elements, Vector Crypto instructions that use elements groups
(See <<crypto-vector-element-groups>>) require that these values are a multiple of the Element Group Size (EGS).
An attempt to execute these instructions with values of `vl` or `vstart` that violate these constraints will raise an
illegal instruction exception.

* vaes*, vsha2*, vghmac, vsm4*: vl and vstart must be multiple of 4
* vsm3*, vl and vstart must be multiple of 8

SEW constraints::
Some Vector Crypto instructions are only defined for specific `SEW`, all other values reserved.

* vaes*, vghmac, vsm4*, vsm3*: SEW must be equal to 32
* vsha2:
** if `Zknha` is implemented: SEW must be equal to 32 
** if `Zknhb` is implemented: SEW must be either to 32 or 64 
* vclmul and vclmulh: SEW must be equal to 64-bit

Source/Destination overlap constraints::
Some Vector Crypto instructions have overlap constraints. Encodings that violate these constraints are reserved.
* vaes*.vs: the single register vs2 cannot overlap with the register group vd
* vsm4r.vs: the single register vs2 cannot overlap with the register group vd
* vsha2c[hl].vv and vsha2ms.vv: vd cannot overlap with either vs1 or vs2
* vsm3me.vv: the case where the register group vd overlaps with the register group vs2 is reserved
* vsm3c.vi: the case where the register group vd overlaps with the register group vs2 is reserved