[#insns-aes32esi, reftext="AES final round encrypt (RV32)"]
=== aes32esi

Synopsis::
AES final round encryption instruction for RV32.

Mnemonic::
aes32esi rt, rs2, bs

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 0x33},
{bits: 5, name: 0x0},
{bits: 3, name: 0x0},
{bits: 5, name: 'rt'},
{bits: 5, name: 'rs2'},
{bits: 5, name: 0x1b},
{bits: 2, name: 'bs'},
]}
....

Description:: 
This instruction sources a single byte from `rs2` according to `bs`.
To this it applies the forward AES SBox operation,
before XOR'ing the result with `rs1`.

.Architecture Note
[WARNING,caption="SH"]
====
The encoding of this instruction will change in a future release to maintain
consistency with the base ISA.
The `rt` field will be replaced with the normal `rd`,`rs1` fields, making
it a standard R-type instruction.
====

Operation::
[source,sail]
--
function clause execute (AES32ESI(bs, rs2, rt))={
  let rs1_val : xlenbits = X(rt);
  let rs2_val : xlenbits = X(rs2);
  let shamt   : bits(6)  = (0b0 @ bs @ 0b000); /* shamt = bs*8 */
  let si      : bits(8)  = (rs2_val >> shamt)[7..0]; /* SBox Input */
  let so      : bits(8)  = aes_sbox_fwd(si);
  let result  : xlenbits = rs1_val ^ (so << shamt) ^ (so >> (0b100000 - shamt));
  X(rt) = result; RETIRE_SUCCESS
}
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<crypto_scalar_ext_zkne>>
| v0.9.0
| Frozen
|===


